import { fireEvent,render,screen,waitFor,within } from '@testing-library/react';
import { QueryClient,QueryClientProvider } from '@tanstack/react-query';
import { beforeEach,describe,expect,it,vi } from 'vitest';
import { AddClientModal } from '../AddClientModal';
class TestResizeObserver { observe() {} unobserve() {} disconnect() {} }
Object.defineProperty(globalThis,'ResizeObserver',{writable:true,value:TestResizeObserver});
const invoke=vi.fn();
vi.mock('@/lib/secureInvoke',()=>({invokeSecureFunction:(...args:unknown[])=>invoke(...args)}));
vi.mock('@/hooks/useActivityLogger',()=>({logActivityDirect:vi.fn()}));
vi.mock('sonner',()=>({toast:{success:vi.fn(),warning:vi.fn(),error:vi.fn()}}));
vi.mock('@/branding/useBrand',()=>({useBrand:()=>({settings:{id:'11111111-1111-4111-8111-111111111111',companyName:'Aurixa Test',primaryColor:'#' + '12345B',accentColor:'#' + 'C9A227',sidebarLogo:null,authLogo:null,emailSignature:{email:'hello@aurixa.test',phone:'0400 000 000',website:'aurixa.test',address:'Sydney'}}})}));
function setup(props:{open?:boolean;onOpenChange?:(v:boolean)=>void}={}){const client=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}});const onOpenChange=props.onOpenChange??vi.fn();const view=render(<QueryClientProvider client={client}><AddClientModal open={props.open??true} onOpenChange={onOpenChange}/></QueryClientProvider>);return {...view,client,onOpenChange}}
function clickTab(name:string){const tab=screen.getByRole('tab',{name});fireEvent.click(tab);fireEvent.mouseDown(tab,{button:0,ctrlKey:false})}
function advanced(){clickTab('Advanced')}
function factSection(name:string){clickTab(name)}
function activePanel(){return within(document.querySelector<HTMLElement>('[role=tabpanel][data-visible=true]')!)}
function input(label:string,value:string){fireEvent.change(activePanel().getByLabelText(label),{target:{value}})}
beforeEach(()=>{invoke.mockReset();invoke.mockImplementation(async(name:string)=>name==='manage-automation-settings'?{data:{success:true,pipelines:[],stages:[]},error:null}:{data:{success:true},error:null})});
describe('Add Client modes',()=>{
 it('defaults to Standard and retains all legacy fields',()=>{setup();expect(screen.getByRole('tab',{name:'Standard'})).toHaveAttribute('aria-selected','true');for(const label of ['First Name *','Surname *','Current Address','Sync to GoHighLevel after creating'])expect(activePanel().getByLabelText(label)).toBeInTheDocument()});
 it('keeps Standard creation on manage-client-data and the existing GHL sequence',async()=>{const calls:string[]=[];invoke.mockImplementation(async(name:string)=>{calls.push(name);if(name==='manage-automation-settings')return {data:{success:true,pipelines:[],stages:[]},error:null};if(name==='manage-client-data')return {data:{success:true,result:{id:'standard-1'}},error:null};if(name==='sync-client-to-ghl')return {data:{success:true},error:null};return {data:{},error:null}});setup();fireEvent.change(screen.getByLabelText('First Name *'),{target:{value:'Alex'}});fireEvent.change(screen.getByLabelText('Surname *'),{target:{value:'Smith'}});fireEvent.click(screen.getByRole('button',{name:'Create Client'}));await waitFor(()=>expect(calls).toContain('sync-client-to-ghl'));expect(calls).toContain('manage-client-data');expect(calls).not.toContain('create-advanced-client');expect(calls.indexOf('manage-client-data')).toBeLessThan(calls.indexOf('sync-client-to-ghl'))});
 it('renders all four Advanced sections and preserves state while switching',()=>{setup();advanced();for(const name of ['White Label Setup','Client Fact Find','Living Expenses','Client Form Output'])expect(screen.getByRole('tab',{name})).toBeInTheDocument();input('Organisation Name','Session Brand');clickTab('Client Fact Find');clickTab('White Label Setup');clickTab('Standard');clickTab('Advanced');expect(activePanel().getByLabelText('Organisation Name')).toHaveValue('Session Brand')});
 it('resets Advanced state after close and reopen',()=>{const onOpenChange=vi.fn();const view=setup({onOpenChange});advanced();input('Organisation Name','Temporary');fireEvent.click(screen.getByRole('button',{name:'Cancel'}));view.rerender(<QueryClientProvider client={view.client}><AddClientModal open={false} onOpenChange={onOpenChange}/></QueryClientProvider>);view.rerender(<QueryClientProvider client={view.client}><AddClientModal open onOpenChange={onOpenChange}/></QueryClientProvider>);advanced();expect(activePanel().getByLabelText('Organisation Name')).toHaveValue('Aurixa Test')});
 it('renders exactly 10 assets, 8 liabilities, and 50 fixed zero-default expenses',()=>{setup();advanced();clickTab('Client Fact Find');factSection('Assets');expect(screen.getAllByTestId('asset-row')).toHaveLength(10);factSection('Liabilities');expect(screen.queryAllByTestId('asset-row')).toHaveLength(0);expect(screen.getAllByTestId('liability-row')).toHaveLength(8);clickTab('Living Expenses');expect(screen.getAllByTestId('expense-row')).toHaveLength(50);expect(activePanel().getByLabelText('Higher Education / Vocational Training monthly amount')).toHaveValue(0)});
 it('updates asset, debt, applicant income, expense, and output totals from live state',()=>{setup();advanced();clickTab('Client Fact Find');factSection('Employment & Income');fireEvent.change(activePanel().getAllByLabelText('Base Salary — Annual')[0],{target:{value:'50000'}});factSection('Assets');input('Asset 1 Current Value','1000');input('Asset 1 Loan Balance','400');factSection('Liabilities');input('Liability 1 Current Balance','100');expect(screen.getAllByText('$1,000.00').length).toBeGreaterThan(0);expect(screen.getAllByText('$50,000.00').length).toBeGreaterThan(0);clickTab('Living Expenses');input('Childcare monthly amount','250');expect(screen.getAllByText('$250.00').length).toBeGreaterThan(0);clickTab('Client Form Output');expect(screen.getByTestId('output-living-expenses')).toHaveTextContent('$250.00');expect(screen.getAllByText('$500.00').length).toBeGreaterThan(0)});
 it('shows a negative net position with the shared formatter',()=>{setup();advanced();clickTab('Client Fact Find');factSection('Liabilities');input('Liability 1 Current Balance','10');clickTab('Client Form Output');expect(screen.getAllByText('-$10.00').length).toBeGreaterThan(0)});
 it('allows blank Applicant 2 but requires both names after any Applicant 2 value',async()=>{setup();advanced();clickTab('Client Fact Find');fireEvent.change(activePanel().getAllByLabelText('Email')[1],{target:{value:'second@example.com'}});fireEvent.click(screen.getByRole('button',{name:'Review Output'}));await waitFor(()=>expect(activePanel().getByText(/Applicant 2 first name is required/)).toBeVisible());expect(activePanel().getByText(/Applicant 2 surname is required/)).toBeVisible()});
 it('reviews a valid local form in the read-only output without making requests',async()=>{setup();advanced();clickTab('Client Fact Find');fireEvent.change(activePanel().getAllByLabelText(/First Name/)[0],{target:{value:'Alex'}});fireEvent.change(activePanel().getAllByLabelText(/Surname/)[0],{target:{value:'Smith'}});invoke.mockClear();fireEvent.click(screen.getByRole('button',{name:'Review Output'}));await waitFor(()=>expect(screen.getByRole('tab',{name:'Client Form Output'})).toHaveAttribute('data-state','active'));expect(screen.getByTestId('client-output-preview')).toHaveTextContent('Alex Smith');expect(screen.getByTestId('client-output-preview').querySelectorAll('input,select,textarea')).toHaveLength(0);expect(invoke).not.toHaveBeenCalled()});
 it('exposes no Advanced Create Client or GHL controls',()=>{setup();advanced();expect(activePanel().queryByRole('button',{name:'Create Client'})).not.toBeInTheDocument();expect(activePanel().queryByLabelText(/GoHighLevel/i)).not.toBeInTheDocument();expect(screen.getByText('Advanced client saving will be connected separately.')).toBeInTheDocument()});
 it('renders the premium Advanced workspace structure and icon tabs',()=>{setup();advanced();expect(screen.getByTestId('add-client-premium-header')).toBeInTheDocument();expect(screen.getByTestId('premium-mode-tabs')).toBeInTheDocument();expect(screen.getByTestId('advanced-navigation')).toBeInTheDocument();for(const key of ['branding','fact-find','expenses','output'])expect(screen.getByTestId(`advanced-tab-icon-${key}`)).toBeInTheDocument();expect(screen.getByTestId('advanced-content-scroll')).toBeInTheDocument()});
 it('keeps the footer outside the scroll region with only the two Advanced actions',()=>{setup();advanced();const footer=screen.getByTestId('advanced-footer'),scroll=screen.getByTestId('advanced-content-scroll');expect(scroll.contains(footer)).toBe(false);expect(within(footer).getAllByRole('button')).toHaveLength(2);expect(within(footer).getByRole('button',{name:'Cancel'})).toBeVisible();expect(within(footer).getByRole('button',{name:'Review Output'})).toBeVisible()});
 it('mounts only the selected one of five internal Fact Find sections',()=>{setup();advanced();clickTab('Client Fact Find');for(const name of ['Applicants','Address History','Employment & Income','Assets','Liabilities'])expect(screen.getByRole('tab',{name})).toBeInTheDocument();expect(screen.getByRole('tab',{name:'Applicants'})).toHaveAttribute('aria-selected','true');expect(screen.getByTestId('applicant-card-2')).toBeInTheDocument();expect(screen.queryByTestId('assets-table')).not.toBeInTheDocument();factSection('Address History');expect(screen.getByText('Applicant 1 Address History')).toBeInTheDocument();expect(screen.queryByTestId('applicant-card-1')).not.toBeInTheDocument();factSection('Employment & Income');expect(screen.getByText('Applicant 1 Employment and Income')).toBeInTheDocument();expect(screen.queryByTestId('assets-table')).not.toBeInTheDocument()});
 it('preserves applicant and asset values across unmounting sections',()=>{setup();advanced();clickTab('Client Fact Find');fireEvent.change(activePanel().getAllByLabelText('First Name')[0],{target:{value:'Alex'}});factSection('Assets');input('Asset 1 Current Value','123');factSection('Applicants');expect(activePanel().getAllByLabelText('First Name')[0]).toHaveValue('Alex');factSection('Assets');expect(activePanel().getByLabelText('Asset 1 Current Value')).toHaveValue(123)});
 it('uses responsive applicant cards and local native table scroll regions',()=>{setup();advanced();clickTab('Client Fact Find');expect(screen.getByTestId('applicant-responsive-grid')).toHaveClass('xl:grid-cols-2');expect(screen.getByTestId('applicant-card-2')).toHaveTextContent('Optional');factSection('Assets');expect(screen.getByTestId('assets-horizontal-scroll')).toHaveClass('overflow-x-auto');factSection('Liabilities');expect(screen.getByTestId('liabilities-horizontal-scroll')).toHaveClass('overflow-x-auto')});
 it('resets only the modal content scroll position when switching internal sections',()=>{setup();advanced();clickTab('Client Fact Find');const scroll=screen.getByTestId('advanced-content-scroll');scroll.scrollTop=240;factSection('Assets');expect(scroll.scrollTop).toBe(0)});
 it('navigates validation to the internal section before focusing errors',async()=>{setup();advanced();clickTab('Client Fact Find');factSection('Assets');input('Asset 1 Current Value','-1');factSection('Applicants');fireEvent.click(screen.getByRole('button',{name:'Review Output'}));await waitFor(()=>expect(screen.getByRole('tab',{name:'Assets'})).toHaveAttribute('aria-selected','true'));expect(activePanel().getByLabelText('Asset 1 Current Value')).toBeInTheDocument()});
 it('substantially limits mounted inputs to the active internal section',()=>{const count=()=>screen.getByRole('tabpanel',{name:/Applicants|Address History|Employment & Income|Assets|Liabilities/}).querySelectorAll('input').length;setup();advanced();clickTab('Client Fact Find');expect(count()).toBe(20);factSection('Address History');expect(count()).toBe(8);factSection('Employment & Income');expect(count()).toBe(20);factSection('Assets');expect(count()).toBe(100);factSection('Liabilities');expect(count()).toBe(80)});
});
