import { fireEvent,render,screen,waitFor,within } from '@testing-library/react';
import { QueryClient,QueryClientProvider } from '@tanstack/react-query';
import { beforeEach,describe,expect,it,vi } from 'vitest';
import * as XLSX from 'xlsx';
import { AddClientModal } from '../AddClientModal';
import { LIVING_EXPENSE_ITEMS } from '@/lib/client-fact-find/fieldDefinitions';
class TestResizeObserver { observe() {} unobserve() {} disconnect() {} }
Object.defineProperty(globalThis,'ResizeObserver',{writable:true,value:TestResizeObserver});
const invoke=vi.fn();
vi.mock('@/lib/secureInvoke',()=>({invokeSecureFunction:(...args:unknown[])=>invoke(...args)}));
vi.mock('@/hooks/useActivityLogger',()=>({logActivityDirect:vi.fn()}));
vi.mock('@/hooks/useSecureStorage',()=>({secureStorageUpload:vi.fn().mockResolvedValue({success:true,path:'client-1/import.xlsx'})}));
vi.mock('sonner',()=>({toast:{success:vi.fn(),warning:vi.fn(),error:vi.fn()}}));
vi.mock('@/branding/useBrand',()=>({useBrand:()=>({settings:{id:'11111111-1111-4111-8111-111111111111',companyName:'Aurixa Test',primaryColor:'#' + '12345B',accentColor:'#' + 'C9A227',sidebarLogo:null,authLogo:null,emailSignature:{email:'hello@aurixa.test',phone:'0400 000 000',website:'aurixa.test',address:'Sydney'}}})}));
function setup(props:{open?:boolean;onOpenChange?:(v:boolean)=>void}={}){const client=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}});const onOpenChange=props.onOpenChange??vi.fn();const view=render(<QueryClientProvider client={client}><AddClientModal open={props.open??true} onOpenChange={onOpenChange}/></QueryClientProvider>);return {...view,client,onOpenChange}}
function clickTab(name:string){const tab=screen.getByRole('tab',{name});fireEvent.click(tab);fireEvent.mouseDown(tab,{button:0,ctrlKey:false})}
function advanced(){clickTab('Advanced')}
function factSection(name:string){clickTab(name)}
function activePanel(){return within(document.querySelector<HTMLElement>('[role=tabpanel][data-visible=true]')!)}
function input(label:string,value:string){fireEvent.change(activePanel().getByLabelText(label),{target:{value}})}
function advancedField(name:string){return document.querySelector<HTMLInputElement>(`[name="${name}"]`)!}
function completedWorkbookFile(){
 const book=XLSX.utils.book_new(),fact=XLSX.utils.aoa_to_sheet([]),expenses=XLSX.utils.aoa_to_sheet([]);
 Object.assign(fact,{C6:{t:'s',v:'Ms'},C7:{t:'s',v:'Avery'},C9:{t:'s',v:'Nguyen'},C10:{t:'s',v:'15/04/1987'},C15:{t:'s',v:'0412345678'},C16:{t:'s',v:'avery@example.test'},G6:{t:'s',v:'Mr'},G7:{t:'s',v:'Jordan'},G9:{t:'s',v:'Nguyen'},G10:{t:'s',v:'20/08/1985'},G15:{t:'s',v:'0498765432'},G16:{t:'s',v:'jordan@example.test'},C19:{t:'s',v:'11 Harbour Street'},C20:{t:'s',v:'Owned'},G19:{t:'s',v:'22 Garden Avenue'},G20:{t:'s',v:'Mortgaged'},C27:{t:'s',v:'Permanent'},C28:{t:'s',v:'Aurixa Systems'},C29:{t:'s',v:'Director'},C32:{t:'n',v:140000},G27:{t:'s',v:'Self-employed'},G28:{t:'s',v:'Nguyen Studio'},G29:{t:'s',v:'Designer'},G32:{t:'n',v:95000}});
 for(let index=0;index<10;index++){const row=40+index;fact[`A${row}`]={t:'s',v:`Imported Asset ${index+1}`};fact[`B${row}`]={t:'s',v:`Asset description ${index+1}`};fact[`D${row}`]={t:'n',v:(index+1)*100000};}
 for(let index=0;index<8;index++){const row=53+index;fact[`A${row}`]={t:'s',v:`Imported Liability ${index+1}`};fact[`B${row}`]={t:'s',v:`Lender ${index+1}`};fact[`F${row}`]={t:'n',v:(index+1)*1000};}
 fact['!ref']='A1:J60';
 LIVING_EXPENSE_ITEMS.forEach((item,index)=>{const row=index+5;expenses[`A${row}`]={t:'s',v:item.category};expenses[`B${row}`]={t:'s',v:item.itemLabel};expenses[`C${row}`]={t:'n',v:index+1};expenses[`D${row}`]={t:'s',v:`Imported note ${index+1}`};});expenses['!ref']='A1:D55';
 XLSX.utils.book_append_sheet(book,fact,'Client Fact Find');XLSX.utils.book_append_sheet(book,expenses,'Living Expenses');
 const bytes=XLSX.write(book,{type:'array',bookType:'xlsx'}) as ArrayBuffer,file=new File([bytes],'completed-client-fact-find.xlsx',{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});Object.defineProperty(file,'arrayBuffer',{value:async()=>bytes});return file;
}
function dropWorkbook(file:File){fireEvent.drop(screen.getByTestId('excel-dropzone'),{dataTransfer:{files:[file],items:[{kind:'file',type:file.type,getAsFile:()=>file}],types:['Files']}})}
beforeEach(()=>{invoke.mockReset();invoke.mockImplementation(async(name:string)=>name==='manage-automation-settings'?{data:{success:true,pipelines:[],stages:[]},error:null}:{data:{success:true},error:null})});
describe('Add Client modes',()=>{
 it('defaults to Standard and retains all legacy fields',()=>{setup();expect(screen.getByRole('tab',{name:'Standard'})).toHaveAttribute('aria-selected','true');for(const label of ['First Name *','Surname *','Current Address','Sync to GoHighLevel after creating'])expect(activePanel().getByLabelText(label)).toBeInTheDocument()});
 it('keeps Standard creation on manage-client-data and the existing GHL sequence',async()=>{const calls:string[]=[];invoke.mockImplementation(async(name:string)=>{calls.push(name);if(name==='manage-automation-settings')return {data:{success:true,pipelines:[],stages:[]},error:null};if(name==='manage-client-data')return {data:{success:true,result:{id:'standard-1'}},error:null};if(name==='sync-client-to-ghl')return {data:{success:true},error:null};return {data:{},error:null}});setup();fireEvent.change(screen.getByLabelText('First Name *'),{target:{value:'Alex'}});fireEvent.change(screen.getByLabelText('Surname *'),{target:{value:'Smith'}});fireEvent.click(screen.getByRole('button',{name:'Create Client'}));await waitFor(()=>expect(calls).toContain('sync-client-to-ghl'));expect(calls).toContain('manage-client-data');expect(calls).not.toContain('create-advanced-client');expect(calls.indexOf('manage-client-data')).toBeLessThan(calls.indexOf('sync-client-to-ghl'))});
 it('renders exactly four Advanced sections and removes White Label Setup',()=>{setup();advanced();expect(screen.getAllByRole('tab').filter(tab=>['Excel Import','Client Fact Find','Living Expenses','Client Form Output'].includes(tab.textContent||'')).map(tab=>tab.textContent)).toEqual(['Excel Import','Client Fact Find','Living Expenses','Client Form Output']);expect(screen.queryByRole('tab',{name:'White Label Setup'})).not.toBeInTheDocument()});
 it('resets Advanced state after close and reopen',()=>{const onOpenChange=vi.fn();const view=setup({onOpenChange});advanced();clickTab('Client Fact Find');fireEvent.change(activePanel().getAllByLabelText('First Name')[0],{target:{value:'Temporary'}});fireEvent.click(screen.getByRole('button',{name:'Cancel'}));view.rerender(<QueryClientProvider client={view.client}><AddClientModal open={false} onOpenChange={onOpenChange}/></QueryClientProvider>);view.rerender(<QueryClientProvider client={view.client}><AddClientModal open onOpenChange={onOpenChange}/></QueryClientProvider>);advanced();clickTab('Client Fact Find');expect(activePanel().getAllByLabelText('First Name')[0]).toHaveValue('')});
 it('renders exactly 10 assets, 8 liabilities, and one continuous 50-row expense worksheet',()=>{setup();advanced();clickTab('Client Fact Find');factSection('Assets');expect(screen.getAllByTestId('asset-card')).toHaveLength(10);factSection('Liabilities');expect(screen.queryAllByTestId('asset-card')).toHaveLength(0);expect(screen.getAllByTestId('liability-card')).toHaveLength(8);clickTab('Living Expenses');expect(screen.getAllByTestId('expense-row')).toHaveLength(50);const list=screen.getByTestId('expense-continuous-list');expect(list).toBeInTheDocument();expect(list).toHaveClass('overflow-hidden');expect(list).not.toHaveClass('overflow-x-auto');expect(screen.getAllByTestId('expense-list-header')).toHaveLength(1);for(const heading of ['Category','Expense Item','Monthly Amount','Notes'])expect(screen.getByTestId('expense-list-header')).toHaveTextContent(heading);expect(activePanel().getByLabelText('Higher Education / Vocational Training monthly amount')).toHaveValue(0)});
 it('updates asset, debt, applicant income, expense, and output totals from live state',()=>{setup();advanced();clickTab('Client Fact Find');factSection('Employment & Income');fireEvent.change(activePanel().getAllByLabelText('Base Salary — Annual')[0],{target:{value:'50000'}});factSection('Assets');input('Asset 1 Current Value','1000');input('Asset 1 Loan Balance','400');factSection('Liabilities');input('Liability 1 Current Balance','100');expect(screen.getAllByText('$1,000.00').length).toBeGreaterThan(0);expect(screen.getAllByText('$50,000.00').length).toBeGreaterThan(0);clickTab('Living Expenses');input('Childcare monthly amount','250');expect(screen.getAllByText('$250.00').length).toBeGreaterThan(0);clickTab('Client Form Output');expect(screen.getByTestId('output-living-expenses')).toHaveTextContent('$250.00');expect(screen.getAllByText('$500.00').length).toBeGreaterThan(0)});
 it('shows a negative net position with the shared formatter',()=>{setup();advanced();clickTab('Client Fact Find');factSection('Liabilities');input('Liability 1 Current Balance','10');clickTab('Client Form Output');expect(screen.getAllByText('-$10.00').length).toBeGreaterThan(0)});
 it('opens incomplete current values directly in output and returns to the previous form tab',()=>{setup();advanced();clickTab('Client Fact Find');fireEvent.change(activePanel().getAllByLabelText('Email')[1],{target:{value:'second@example.com'}});fireEvent.click(screen.getByRole('button',{name:'Review Output'}));expect(screen.getByTestId('client-output-preview')).toHaveTextContent('second@example.com');expect(screen.getByTestId('client-output-preview')).toHaveTextContent('—');fireEvent.click(screen.getByRole('button',{name:'Back to Form'}));expect(screen.getByRole('tab',{name:'Client Fact Find'})).toHaveAttribute('data-state','active')});
 it('reviews a valid local form in the read-only output without making requests',async()=>{setup();advanced();clickTab('Client Fact Find');fireEvent.change(activePanel().getAllByLabelText(/First Name/)[0],{target:{value:'Alex'}});fireEvent.change(activePanel().getAllByLabelText(/Surname/)[0],{target:{value:'Smith'}});invoke.mockClear();fireEvent.click(screen.getByRole('button',{name:'Review Output'}));await waitFor(()=>expect(screen.getByRole('tab',{name:'Client Form Output'})).toHaveAttribute('data-state','active'));expect(screen.getByTestId('client-output-preview')).toHaveTextContent('Alex Smith');expect(screen.getByTestId('client-output-preview').querySelectorAll('input,select,textarea')).toHaveLength(0);expect(invoke).not.toHaveBeenCalled()});
 it('does not render document colour controls or colour output text',()=>{setup();advanced();expect(activePanel().queryByText('Primary Colour')).not.toBeInTheDocument();expect(activePanel().queryByText('Accent Colour')).not.toBeInTheDocument();expect(activePanel().queryByLabelText(/picker/i)).not.toBeInTheDocument();expect(activePanel().queryByLabelText(/hex value/i)).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Review Output'}));expect(screen.getByTestId('client-output-preview')).not.toHaveTextContent(/Primary|Accent/)});
 it('renders the output as exactly five ordered unbranded sections from Portfolio Summary to Declaration',()=>{setup();advanced();fireEvent.click(screen.getByRole('button',{name:'Review Output'}));const output=screen.getByTestId('client-output-preview'),sections=Array.from(output.querySelectorAll<HTMLElement>('[data-output-section]'));expect(sections.map(section=>section.dataset.outputSection)).toEqual(['Portfolio Summary','Applicant Details','Employment & Income','Financial Summary','Declaration']);expect(sections[0]).toHaveTextContent(/^Portfolio Summary/);expect(sections.at(-1)).toHaveTextContent(/^Declaration/);for(const branding of ['Organisation','Trading Name','Confidentiality','Document Title','Prepared By','Version','Website','Business Address','Logo'])expect(output).not.toHaveTextContent(branding)});
 it('exposes Advanced Create Client without GHL controls',()=>{setup();advanced();expect(screen.getByRole('button',{name:'Create Client'})).toBeInTheDocument();expect(activePanel().queryByLabelText(/GoHighLevel/i)).not.toBeInTheDocument()});
 it('renders the local Excel import surface and Vite-managed template download',()=>{setup();advanced();expect(screen.getByTestId('excel-import-tab')).toBeInTheDocument();expect(screen.getByTestId('excel-dropzone')).toHaveTextContent('.xlsx or .xls');const link=screen.getByRole('link',{name:/Download Template/});expect(link.getAttribute('href')).toMatch(/Aurixa.*Client.*Fact.*Find.*Template.*\.xlsx/);expect(link).toHaveAttribute('download','Aurixa-Systems-Client-Fact-Find-Template.xlsx')});
 it('uploads, applies and visibly exposes the complete workbook across every editable Advanced section',async()=>{setup();advanced();invoke.mockClear();dropWorkbook(completedWorkbookFile());await screen.findByText('completed-client-fact-find.xlsx');expect(invoke).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Review Imported Data'}));await waitFor(()=>expect(screen.getByRole('tab',{name:'Client Fact Find'})).toHaveAttribute('data-state','active'));expect(screen.getByRole('tab',{name:'Applicants'})).toHaveAttribute('aria-selected','true');expect(advancedField('applicants.0.firstName')).toHaveValue('Avery');expect(advancedField('applicants.1.firstName')).toHaveValue('Jordan');factSection('Address History');expect(advancedField('addresses.0.address')).toHaveValue('11 Harbour Street');expect(advancedField('addresses.2.address')).toHaveValue('22 Garden Avenue');factSection('Employment & Income');expect(advancedField('employment.0.employerOrBusiness')).toHaveValue('Aurixa Systems');expect(advancedField('employment.1.employerOrBusiness')).toHaveValue('Nguyen Studio');factSection('Assets');expect(activePanel().getByLabelText('Asset 1 Asset Type')).toHaveValue('Imported Asset 1');expect(activePanel().getByLabelText('Asset 10 Current Value')).toHaveValue(1000000);factSection('Liabilities');expect(activePanel().getByLabelText('Liability 1 Liability Type')).toHaveValue('Imported Liability 1');expect(activePanel().getByLabelText('Liability 8 Current Balance')).toHaveValue(8000);clickTab('Living Expenses');expect(screen.getAllByTestId('expense-row')).toHaveLength(50);expect(activePanel().getByLabelText('Childcare monthly amount')).toHaveValue(1);expect(activePanel().getByLabelText('Other Regular Expense monthly amount')).toHaveValue(50);expect(activePanel().getByLabelText('Other Regular Expense notes')).toHaveValue('Imported note 50');input('Childcare monthly amount','321');input('Childcare notes','Edited after import');clickTab('Client Form Output');expect(screen.getByTestId('client-output-preview')).toHaveTextContent('Avery Nguyen');expect(screen.getByTestId('client-output-preview')).toHaveTextContent('Aurixa Systems');expect(screen.getByTestId('output-living-expenses')).toHaveTextContent('$1,595.00');expect(invoke).not.toHaveBeenCalled()});

  it('validates Advanced required names and navigates to Applicants without creating',async()=>{setup();advanced();invoke.mockClear();fireEvent.click(screen.getByRole('button',{name:'Create Client'}));await waitFor(()=>expect(screen.getByRole('tab',{name:'Client Fact Find'})).toHaveAttribute('data-state','active'));expect(screen.getByRole('tab',{name:'Applicants'})).toHaveAttribute('aria-selected','true');expect(screen.getByTestId('fact-find-sticky-navigation')).toHaveClass('sticky','top-0','z-20','bg-background');expect(screen.getByText('Primary first name is required')).toBeInTheDocument();expect(invoke).not.toHaveBeenCalled()});
 it('renders the premium Advanced workspace structure and icon tabs',()=>{setup();advanced();expect(screen.getByTestId('add-client-premium-header')).toBeInTheDocument();expect(screen.getByTestId('premium-mode-tabs')).toBeInTheDocument();expect(screen.getByTestId('advanced-navigation')).toBeInTheDocument();for(const key of ['excel','fact-find','expenses','output'])expect(screen.getByTestId(`advanced-tab-icon-${key}`)).toBeInTheDocument();expect(screen.getByTestId('advanced-content-scroll')).toBeInTheDocument()});
 it('keeps the footer outside the scroll region with all three Advanced actions',()=>{setup();advanced();const footer=screen.getByTestId('advanced-footer'),scroll=screen.getByTestId('advanced-content-scroll');expect(scroll.contains(footer)).toBe(false);expect(within(footer).getAllByRole('button')).toHaveLength(3);for(const name of ['Cancel','Review Output','Create Client'])expect(within(footer).getByRole('button',{name})).toBeVisible()});
  it('mounts only the selected one of five internal Fact Find sections',()=>{setup();advanced();clickTab('Client Fact Find');for(const name of ['Applicants','Address History','Employment & Income','Assets','Liabilities'])expect(screen.getByRole('tab',{name})).toBeInTheDocument();expect(screen.getByRole('tab',{name:'Applicants'})).toHaveAttribute('aria-selected','true');const navigation=screen.getByTestId('fact-find-sticky-navigation');expect(navigation).toHaveClass('sticky','top-0','z-20','bg-background');expect(navigation.compareDocumentPosition(screen.getByTestId('fact-find-summary'))&Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();expect(screen.getByTestId('applicant-card-2')).toBeInTheDocument();expect(screen.queryByTestId('assets-table')).not.toBeInTheDocument();factSection('Address History');expect(screen.getByText('Applicant 1 Address History')).toBeInTheDocument();expect(screen.queryByTestId('applicant-card-1')).not.toBeInTheDocument();factSection('Employment & Income');expect(screen.getByText('Applicant 1 Employment and Income')).toBeInTheDocument();expect(screen.queryByTestId('assets-table')).not.toBeInTheDocument()});
 it('preserves applicant and asset values across unmounting sections',()=>{setup();advanced();clickTab('Client Fact Find');fireEvent.change(activePanel().getAllByLabelText('First Name')[0],{target:{value:'Alex'}});factSection('Assets');input('Asset 1 Current Value','123');factSection('Applicants');expect(activePanel().getAllByLabelText('First Name')[0]).toHaveValue('Alex');factSection('Assets');expect(activePanel().getByLabelText('Asset 1 Current Value')).toHaveValue(123)});
 it('uses responsive cards without horizontal scroll regions',()=>{setup();advanced();clickTab('Client Fact Find');expect(screen.getByTestId('applicant-responsive-grid')).toHaveClass('xl:grid-cols-2');expect(screen.getByTestId('applicant-card-2')).toHaveTextContent('Optional');factSection('Assets');expect(screen.getAllByTestId('asset-card')).toHaveLength(10);expect(screen.queryByTestId('assets-horizontal-scroll')).not.toBeInTheDocument();factSection('Liabilities');expect(screen.getAllByTestId('liability-card')).toHaveLength(8);expect(screen.queryByTestId('liabilities-horizontal-scroll')).not.toBeInTheDocument()});
 it('resets only the modal content scroll position when switching internal sections',()=>{setup();advanced();clickTab('Client Fact Find');const scroll=screen.getByTestId('advanced-content-scroll');scroll.scrollTop=240;factSection('Assets');expect(scroll.scrollTop).toBe(0)});
 it('does not validate or redirect Review Output when values are invalid',()=>{setup();advanced();clickTab('Client Fact Find');factSection('Assets');input('Asset 1 Current Value','-1');fireEvent.click(screen.getByRole('button',{name:'Review Output'}));expect(screen.getByRole('tab',{name:'Client Form Output'})).toHaveAttribute('data-state','active');expect(screen.getByTestId('client-output-preview')).toBeInTheDocument()});
 it('substantially limits mounted inputs to the active internal section',()=>{const count=()=>screen.getByRole('tabpanel',{name:/Applicants|Address History|Employment & Income|Assets|Liabilities/}).querySelectorAll('input').length;setup();advanced();clickTab('Client Fact Find');expect(count()).toBe(20);factSection('Address History');expect(count()).toBe(8);factSection('Employment & Income');expect(count()).toBe(20);factSection('Assets');expect(count()).toBe(100);factSection('Liabilities');expect(count()).toBe(80)});
});
