import { fireEvent,render,screen,waitFor,within } from '@testing-library/react';
import { QueryClient,QueryClientProvider } from '@tanstack/react-query';
import { beforeEach,describe,expect,it,vi } from 'vitest';
import { AddClientModal } from '../AddClientModal';
class TestResizeObserver { observe() {} unobserve() {} disconnect() {} }
Object.defineProperty(globalThis,'ResizeObserver',{writable:true,value:TestResizeObserver});
const invoke=vi.fn();
vi.mock('@/lib/secureInvoke',()=>({invokeSecureFunction:(...args:unknown[])=>invoke(...args)}));
vi.mock('@/hooks/useActivityLogger',()=>({logActivityDirect:vi.fn()}));
vi.mock('sonner',()=>({toast:{success:vi.fn(),warning:vi.fn(),error:vi.fn()}}));
vi.mock('@/branding/useBrand',()=>({useBrand:()=>({settings:{id:'11111111-1111-4111-8111-111111111111',companyName:'Aurixa Test',primaryColor:'#' + '12345B',accentColor:'#' + 'C9A227',sidebarLogo:null,authLogo:null,emailSignature:{email:'hello@aurixa.test',phone:'0400 000 000',website:'aurixa.test',address:'Sydney'}}})}));
function setup(props:{open?:boolean;onOpenChange?:(v:boolean)=>void}={}){const client=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}});const onOpenChange=props.onOpenChange??vi.fn();const view=render(<QueryClientProvider client={client}><AddClientModal open={props.open??true} onOpenChange={onOpenChange}/></QueryClientProvider>);return {...view,client,onOpenChange}}
function clickTab(name:string){const tab=screen.getByRole('tab',{name});fireEvent.click(tab);fireEvent.mouseDown(tab,{button:0,ctrlKey:false})}
function advanced(){clickTab('Advanced')}
function activePanel(){return within(document.querySelector<HTMLElement>('[role=tabpanel][data-visible=true]')!)}
function input(label:string,value:string){fireEvent.change(activePanel().getByLabelText(label),{target:{value}})}
beforeEach(()=>{invoke.mockReset();invoke.mockImplementation(async(name:string)=>name==='manage-automation-settings'?{data:{success:true,pipelines:[],stages:[]},error:null}:{data:{success:true},error:null})});
describe('Add Client modes',()=>{
 it('defaults to Standard and retains all legacy fields',()=>{setup();expect(screen.getByRole('tab',{name:'Standard'})).toHaveAttribute('aria-selected','true');for(const label of ['First Name *','Surname *','Current Address','Sync to GoHighLevel after creating'])expect(activePanel().getByLabelText(label)).toBeInTheDocument()});
 it('keeps Standard creation on manage-client-data and the existing GHL sequence',async()=>{const calls:string[]=[];invoke.mockImplementation(async(name:string)=>{calls.push(name);if(name==='manage-automation-settings')return {data:{success:true,pipelines:[],stages:[]},error:null};if(name==='manage-client-data')return {data:{success:true,result:{id:'standard-1'}},error:null};if(name==='sync-client-to-ghl')return {data:{success:true},error:null};return {data:{},error:null}});setup();fireEvent.change(screen.getByLabelText('First Name *'),{target:{value:'Alex'}});fireEvent.change(screen.getByLabelText('Surname *'),{target:{value:'Smith'}});fireEvent.click(screen.getByRole('button',{name:'Create Client'}));await waitFor(()=>expect(calls).toContain('sync-client-to-ghl'));expect(calls).toContain('manage-client-data');expect(calls).not.toContain('create-advanced-client');expect(calls.indexOf('manage-client-data')).toBeLessThan(calls.indexOf('sync-client-to-ghl'))});
 it('renders all four Advanced sections and preserves state while switching',()=>{setup();advanced();for(const name of ['White Label Setup','Client Fact Find','Living Expenses','Client Form Output'])expect(screen.getByRole('tab',{name})).toBeInTheDocument();input('Organisation Name','Session Brand');clickTab('Client Fact Find');clickTab('White Label Setup');clickTab('Standard');clickTab('Advanced');expect(activePanel().getByLabelText('Organisation Name')).toHaveValue('Session Brand')});
 it('resets Advanced state after close and reopen',()=>{const onOpenChange=vi.fn();const view=setup({onOpenChange});advanced();input('Organisation Name','Temporary');fireEvent.click(screen.getByRole('button',{name:'Cancel'}));view.rerender(<QueryClientProvider client={view.client}><AddClientModal open={false} onOpenChange={onOpenChange}/></QueryClientProvider>);view.rerender(<QueryClientProvider client={view.client}><AddClientModal open onOpenChange={onOpenChange}/></QueryClientProvider>);advanced();expect(activePanel().getByLabelText('Organisation Name')).toHaveValue('Aurixa Test')});
 it('renders exactly 10 assets, 8 liabilities, and 50 fixed zero-default expenses',()=>{setup();advanced();clickTab('Client Fact Find');expect(screen.getAllByTestId('asset-row')).toHaveLength(10);expect(screen.getAllByTestId('liability-row')).toHaveLength(8);clickTab('Living Expenses');expect(screen.getAllByTestId('expense-row')).toHaveLength(50);expect(activePanel().getByLabelText('Higher Education / Vocational Training monthly amount')).toHaveValue(0)});
 it('updates asset, debt, applicant income, expense, and output totals from live state',()=>{setup();advanced();clickTab('Client Fact Find');input('Asset 1 Current Value','1000');input('Asset 1 Loan Balance','400');input('Liability 1 Current Balance','100');fireEvent.change(activePanel().getAllByLabelText('Base Salary — Annual')[0],{target:{value:'50000'}});expect(screen.getByText('$1,000.00')).toBeInTheDocument();expect(screen.getByText('$400.00')).toBeInTheDocument();expect(screen.getByText('$50,000.00')).toBeInTheDocument();clickTab('Living Expenses');input('Childcare monthly amount','250');expect(screen.getByText('$250.00')).toBeInTheDocument();clickTab('Client Form Output');expect(screen.getByTestId('output-living-expenses')).toHaveTextContent('$250.00');expect(screen.getAllByText('$500.00').length).toBeGreaterThan(0)});
 it('shows a negative net position with the shared formatter',()=>{setup();advanced();clickTab('Client Fact Find');input('Liability 1 Current Balance','10');clickTab('Client Form Output');expect(screen.getAllByText('-$10.00').length).toBeGreaterThan(0)});
 it('allows blank Applicant 2 but navigates to Fact Find when partial Applicant 2 is invalid',async()=>{setup();advanced();clickTab('Client Fact Find');const emails=activePanel().getAllByLabelText('Email');fireEvent.change(emails[1],{target:{value:'second@example.com'}});fireEvent.click(screen.getByRole('button',{name:'Create Client'}));await waitFor(()=>expect(screen.getByTestId('advanced-fact-find-tab')).toBeVisible());expect(invoke).not.toHaveBeenCalledWith('create-advanced-client',expect.anything())});
 it('persists before GHL, invalidates clients, and never retries creation when GHL fails',async()=>{const calls:string[]=[];invoke.mockImplementation(async(name:string)=>{calls.push(name);if(name==='manage-automation-settings')return {data:{success:true,pipelines:[],stages:[]},error:null};if(name==='create-advanced-client')return {data:{success:true,clientId:'client-1',factFindId:'fact-1'},error:null};if(name==='sync-client-to-ghl')return {data:{success:false},error:{message:'failed'}};return {data:{},error:null}});const {client}=setup();const invalidate=vi.spyOn(client,'invalidateQueries');advanced();clickTab('Client Fact Find');const firstNames=activePanel().getAllByLabelText(/First Name/),surnames=activePanel().getAllByLabelText(/Surname/);fireEvent.change(firstNames[0],{target:{value:'Alex'}});fireEvent.change(surnames[0],{target:{value:'Smith'}});fireEvent.click(screen.getByRole('button',{name:'Create Client'}));await waitFor(()=>expect(calls).toContain('sync-client-to-ghl'));expect(calls.indexOf('create-advanced-client')).toBeLessThan(calls.indexOf('sync-client-to-ghl'));expect(calls.filter(x=>x==='create-advanced-client')).toHaveLength(1);expect(invalidate).toHaveBeenCalledWith({queryKey:['clients']})});
 it('does not run GHL after valid Advanced persistence fails',async()=>{invoke.mockImplementation(async(name:string)=>name==='manage-automation-settings'?{data:{success:true,pipelines:[],stages:[]},error:null}:name==='create-advanced-client'?{data:null,error:{message:'failure'}}:{data:{success:true},error:null});setup();advanced();clickTab('Client Fact Find');fireEvent.change(activePanel().getAllByLabelText(/First Name/)[0],{target:{value:'Alex'}});fireEvent.change(activePanel().getAllByLabelText(/Surname/)[0],{target:{value:'Smith'}});fireEvent.click(screen.getByRole('button',{name:'Create Client'}));await waitFor(()=>expect(invoke).toHaveBeenCalledWith('create-advanced-client',expect.anything()));expect(invoke).not.toHaveBeenCalledWith('sync-client-to-ghl',expect.anything())});
 it('does not run GHL or submit malformed data after failed persistence/validation',async()=>{invoke.mockImplementation(async(name:string)=>name==='manage-automation-settings'?{data:{success:true,pipelines:[],stages:[]},error:null}:{data:null,error:{message:'failure'}});setup();advanced();fireEvent.click(screen.getByRole('button',{name:'Create Client'}));await waitFor(()=>expect(screen.getByRole('tab',{name:'Client Fact Find'})).toHaveAttribute('data-state','active'));expect(invoke).not.toHaveBeenCalledWith('create-advanced-client',expect.anything());expect(invoke).not.toHaveBeenCalledWith('sync-client-to-ghl',expect.anything())});
});
