import { useMemo,useState } from 'react'; import { FormProvider,useForm } from 'react-hook-form'; import { zodResolver } from '@hookform/resolvers/zod'; import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query'; import { Loader2,UserPlus } from 'lucide-react'; import { toast } from 'sonner';
import { Tabs,TabsContent } from '@/components/ui/tabs'; import { Button } from '@/components/ui/button'; import { invokeSecureFunction } from '@/lib/secureInvoke'; import { advancedClientCreationSchema } from '@/lib/client-fact-find/schema'; import { calculateFactFindTotals } from '@/lib/client-fact-find/calculations'; import type { AdvancedClientCreationPayload } from '@/lib/client-fact-find/types';
import { createAdvancedDefaults } from './defaults'; import { AdvancedTabNavigation,type AdvancedTab } from './AdvancedTabNavigation'; import { WhiteLabelSetupTab } from './WhiteLabelSetupTab'; import { ClientFactFindTab } from './ClientFactFindTab'; import { LivingExpensesTab } from './LivingExpensesTab'; import { ClientFormOutputTab } from './ClientFormOutputTab'; import { AdvancedGhlControls,type Pipeline,type PipelineStage } from './AdvancedGhlControls';
export function AdvancedClientForm({active,onCancel,onCreated}:{active:boolean;onCancel:()=>void;onCreated:()=>void}){const queryClient=useQueryClient();const methods=useForm<AdvancedClientCreationPayload>({resolver:zodResolver(advancedClientCreationSchema) as any,defaultValues:createAdvancedDefaults(),mode:'onBlur',shouldUnregister:false});const [tab,setTab]=useState<AdvancedTab>('branding');const [sync,setSync]=useState(true),[pipelineId,setPipelineId]=useState(''),[stageId,setStageId]=useState('');
 const {data:pipelines=[],isLoading:pipelinesLoading}=useQuery({queryKey:['ghl-pipelines'],queryFn:async()=>{const {data,error}=await invokeSecureFunction('manage-automation-settings',{operation:'getPipelines'});if(error||!data?.success)throw new Error('Failed to load pipelines');return (data.pipelines||[]) as Pipeline[]},enabled:active&&sync});
 const {data:allStages=[]}=useQuery({queryKey:['ghl-pipeline-stages'],queryFn:async()=>{const {data,error}=await invokeSecureFunction('manage-automation-settings',{operation:'getStages'});if(error||!data?.success)throw new Error('Failed to load pipeline stages');return (data.stages||[]) as PipelineStage[]},enabled:active&&sync});
 const stages=useMemo(()=>allStages.filter(x=>x.pipeline_id===pipelineId).sort((a,b)=>(a.position??0)-(b.position??0)),[allStages,pipelineId]);
 const mutation=useMutation({mutationFn:async(payload:AdvancedClientCreationPayload)=>{const totals=calculateFactFindTotals(payload);const {data,error}=await invokeSecureFunction('create-advanced-client',{payload:{...payload,syncToGhl:sync,calculatedTotals:totals}});if(error||!data?.success||!data.clientId)throw new Error('Unable to create the Advanced client securely.');const persisted={clientId:data.clientId as string,factFindId:data.factFindId as string};let synced=false,failed=false;if(sync){const syncPayload:any={clientId:persisted.clientId};if(stageId){const stage=stages.find(x=>x.id===stageId),pipeline=pipelines.find(x=>x.id===stage?.pipeline_id);if(stage)syncPayload.pipelineStageGhlId=stage.ghl_id;if(pipeline?.ghl_id)syncPayload.pipelineGhlId=pipeline.ghl_id}const result=await invokeSecureFunction('sync-client-to-ghl',syncPayload);synced=!result.error&&result.data?.success===true;failed=!synced}return {...persisted,synced,failed}},onSuccess:async result=>{await queryClient.invalidateQueries({queryKey:['clients']});if(result.failed)toast.warning('Client created but failed to sync to GoHighLevel');else if(result.synced)toast.success('Client and fact find created and synced to GoHighLevel');else toast.success('Client and fact find created successfully');methods.reset(createAdvancedDefaults());onCreated()},onError:()=>toast.error('Failed to create client. Please review the form and try again.')});
 const invalid=(errors:any)=>{const first=Object.keys(errors)[0];setTab(first==='branding'?'branding':first==='expenses'?'expenses':'fact-find');requestAnimationFrame(()=>document.querySelector<HTMLElement>('[aria-invalid="true"]')?.focus())};
 const submit=methods.handleSubmit(values=>mutation.mutate(values),invalid);
 return <FormProvider {...methods}><form onSubmit={submit} className="flex min-h-0 flex-1 flex-col"><Tabs value={tab} onValueChange={v=>setTab(v as AdvancedTab)} className="flex min-h-0 flex-1 flex-col"><AdvancedTabNavigation/><div className="min-h-0 flex-1 overflow-y-auto px-4 py-5 sm:px-6"><TabsContent value="branding" className="m-0"><WhiteLabelSetupTab/></TabsContent><TabsContent value="fact-find" className="m-0"><ClientFactFindTab/></TabsContent><TabsContent value="expenses" className="m-0"><LivingExpensesTab/></TabsContent><TabsContent value="output" className="m-0"><ClientFormOutputTab/></TabsContent></div></Tabs><footer className="sticky bottom-0 z-30 shrink-0 border-t border-border bg-background/95 px-4 py-3 backdrop-blur sm:px-6"><div className="mx-auto flex max-w-[1400px] flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><AdvancedGhlControls sync={sync} setSync={setSync} pipelines={pipelines} stages={stages} pipelineId={pipelineId} setPipelineId={setPipelineId} stageId={stageId} setStageId={setStageId} loading={pipelinesLoading}/><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={onCancel}>Cancel</Button><Button type="submit" disabled={mutation.isPending}>{mutation.isPending?<><Loader2 className="mr-2 h-4 w-4 animate-spin"/>Creating...</>:<><UserPlus className="mr-2 h-4 w-4"/>Create Client</>}</Button></div></div></footer></form></FormProvider>}
