import { useFormContext } from 'react-hook-form';
import { ArrowLeft } from 'lucide-react';
import { Button } from '@/components/ui/button';
import type { AdvancedClientCreationPayload } from '@/lib/client-fact-find/types';
import { calculateFactFindTotals,centsToDisplay,formatNetPosition,fullApplicantName } from '@/lib/client-fact-find/calculations';
const DECLARATION="The information contained in this fact find has been provided for the purpose of assessing the client's financial position and coordinating with authorised finance and property professionals. It does not constitute credit assistance, financial product advice or legal advice. The client should verify all information before relying on the generated document.";
export function ClientFormOutputTab({onBack}:{onBack:()=>void}){const {getValues}=useFormContext<AdvancedClientCreationPayload>();const v=getValues(),t=calculateFactFindTotals(v);return <div className="space-y-4"><Button type="button" variant="outline" onClick={onBack}><ArrowLeft className="mr-2 h-4 w-4"/>Back to Form</Button><article data-testid="client-output-preview" className="mx-auto max-w-5xl rounded-2xl border border-border bg-card p-6 shadow-sm sm:p-8">
<section><h2 className="mb-4 text-xl font-semibold">Portfolio Summary</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Summary label="Total Assets" value={centsToDisplay(t.totalAssetsCents)}/><Summary label="Total Debt" value={centsToDisplay(t.totalDebtCents)}/><Summary label="Net Position" value={formatNetPosition(t.netPositionCents)}/><Summary label="Monthly Living Expenses" value={centsToDisplay(t.totalMonthlyLivingExpensesCents)} testId="output-living-expenses"/></div></section>
<section className="mt-8"><h2 className="mb-4 text-lg font-semibold">Applicant Details</h2><div className="grid gap-4 lg:grid-cols-2">{v.applicants.map(a=>{const address=v.addresses.find(x=>x.applicantNumber===a.applicantNumber&&x.addressType==='current');return <div className="rounded-xl border border-border p-4" key={a.applicantNumber}><h3 className="font-semibold">Applicant {a.applicantNumber}{a.applicantNumber===2?' · Optional':''}</h3><dl className="mt-3 grid grid-cols-2 gap-3 text-sm"><Detail label="Full Name" value={fullApplicantName(a)}/><Detail label="Date of Birth" value={a.dateOfBirth||''}/><Detail label="Mobile" value={a.mobile}/><Detail label="Email" value={a.email}/><Detail label="Current Address" value={address?.address||''}/><Detail label="Living Situation" value={address?.livingSituation||''}/></dl></div>})}</div></section>
<section className="mt-8"><h2 className="mb-4 text-lg font-semibold">Employment &amp; Income</h2><div className="grid gap-4 lg:grid-cols-2">{v.applicants.map((a,index)=>{const job=v.employment.find(x=>x.applicantNumber===a.applicantNumber),income=index===0?t.applicant1AnnualIncomeCents:t.applicant2AnnualIncomeCents;return <div className="rounded-xl border border-border p-4" key={a.applicantNumber}><h3 className="font-semibold">Applicant {a.applicantNumber}</h3><dl className="mt-3 grid grid-cols-2 gap-3 text-sm"><Detail label="Employment Type" value={job?.employmentType||''}/><Detail label="Employer / Business" value={job?.employerOrBusiness||''}/><Detail label="Role / Position" value={job?.roleOrPosition||''}/><Detail label="Start Date" value={job?.startDate||''}/><Detail label="Total Annual Income" value={centsToDisplay(income)}/></dl></div>})}</div></section>
<section className="mt-8"><h2 className="mb-4 text-lg font-semibold">Financial Summary</h2><div className="overflow-hidden rounded-xl border border-border"><SummaryRow label="Total Assets" value={centsToDisplay(t.totalAssetsCents)}/><SummaryRow label="Asset-Linked Debt" value={centsToDisplay(t.totalAssetLinkedDebtCents)}/><SummaryRow label="Other Liabilities" value={centsToDisplay(t.totalOtherLiabilitiesCents)}/><SummaryRow label="Total Debt" value={centsToDisplay(t.totalDebtCents)}/><SummaryRow label="Monthly Living Expenses" value={centsToDisplay(t.totalMonthlyLivingExpensesCents)}/><SummaryRow label="Net Position" value={formatNetPosition(t.netPositionCents)}/></div></section>
<section className="mt-8 rounded-xl border border-border bg-muted/30 p-4"><h2 className="font-semibold">Declaration</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{DECLARATION}</p><div className="mt-8 grid gap-6 sm:grid-cols-2"><p>Client Signature: __________________________</p><p>Date: ____ / ____ / ______</p></div></section>
</article></div>}
function Summary({label,value,testId}:{label:string;value:string;testId?:string}){const negative=label==='Net Position'&&value.startsWith('-');return <div className="rounded-xl border border-border bg-muted/30 p-4"><p className="text-xs text-muted-foreground">{label}</p><p data-testid={testId} className={`mt-1 text-lg font-semibold ${negative?'text-destructive':''}`}>{value}</p></div>};function Detail({label,value}:{label:string;value:string}){return <div><dt className="text-xs text-muted-foreground">{label}</dt><dd className="mt-0.5 break-words">{value||'—'}</dd></div>};function SummaryRow({label,value}:{label:string;value:string}){const negative=label==='Net Position'&&value.startsWith('-');return <div className="flex justify-between border-b border-border px-4 py-3 last:border-0"><span>{label}</span><strong className={negative?'text-destructive':undefined}>{value}</strong></div>}
