import { useCallback, useState } from 'react';
import { AlertTriangle, CheckCircle2, Download, FileSpreadsheet, Loader2, Trash2, UploadCloud } from 'lucide-react';
import { useDropzone } from 'react-dropzone';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog';
import type { ParsedExcelImport } from '@/lib/client-fact-find/excelImport';

const ADVANCED_TEMPLATE_URL = new URL(
  '../../../../docs/reference/Aurixa Systems - White Label Client Fact Find Template.xlsx',
  import.meta.url
).href;
const MAX_EXCEL_FILE_BYTES=10*1024*1024;
const EXCEL_ACCEPT={'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':['.xlsx'],'application/vnd.ms-excel':['.xls']};
const validateExcelFile=(file:Pick<File,'name'|'size'>)=>!/\.(xlsx|xls)$/i.test(file.name)?'Unsupported file type. Select an .xlsx or .xls workbook.':file.size>MAX_EXCEL_FILE_BYTES?'The workbook is larger than the 10 MB maximum.':null;

export function ExcelImportTab({file,onFileChange,hasFormValues,onApply}:{file:File|null;onFileChange:(file:File|null)=>void;hasFormValues:boolean;onApply:(parsed:ParsedExcelImport)=>void}){
  const [parsed,setParsed]=useState<ParsedExcelImport|null>(null),[error,setError]=useState(''),[parsing,setParsing]=useState(false),[confirm,setConfirm]=useState(false);
  const select=useCallback(async(files:File[])=>{const next=files[0];if(!next)return;const invalid=validateExcelFile(next);if(invalid){setError(invalid);setParsed(null);onFileChange(null);return}setParsing(true);setError('');try{const {parseAdvancedClientWorkbook}=await import('@/lib/client-fact-find/excelImport');const result=parseAdvancedClientWorkbook(await next.arrayBuffer());setParsed(result);onFileChange(next)}catch{setParsed(null);onFileChange(null);setError('The workbook could not be imported. Confirm that Client Fact Find and Living Expenses worksheets are present.')}finally{setParsing(false)}},[onFileChange]);
  const {getRootProps,getInputProps,isDragActive,open}=useDropzone({accept:EXCEL_ACCEPT,maxFiles:1,multiple:false,maxSize:MAX_EXCEL_FILE_BYTES,noClick:true,onDropAccepted:select,onDropRejected:rejections=>{const candidate=rejections[0]?.file;setParsed(null);onFileChange(null);setError(candidate?.size>MAX_EXCEL_FILE_BYTES?'The workbook is larger than the 10 MB maximum.':'Unsupported file type. Select an .xlsx or .xls workbook.')}});
  const clear=()=>{setParsed(null);setError('');onFileChange(null)};
  const apply=()=>{if(!parsed)return;if(hasFormValues){setConfirm(true);return}onApply(parsed)};
  return <div className="space-y-5" data-testid="excel-import-tab">
    <Card className="rounded-2xl border-border/70 bg-card"><CardHeader className="flex flex-row items-start justify-between gap-4"><div><CardTitle className="flex items-center gap-2"><FileSpreadsheet className="h-5 w-5 text-brand-200"/>Excel Import</CardTitle><p className="mt-2 text-sm text-muted-foreground">Download the original template, complete it, then import one workbook locally. Nothing is uploaded until you create the client.</p></div><Button asChild variant="outline" className="shrink-0 rounded-xl"><a href={ADVANCED_TEMPLATE_URL} download="Aurixa-Systems-Client-Fact-Find-Template.xlsx"><Download className="mr-2 h-4 w-4"/>Download Template</a></Button></CardHeader>
      <CardContent><div {...getRootProps()} data-testid="excel-dropzone" className={`flex min-h-48 flex-col items-center justify-center rounded-2xl border-2 border-dashed p-6 text-center transition-colors ${isDragActive?'border-brand-300 bg-brand-300/10':'border-border bg-muted/20'}`}><input {...getInputProps()} aria-label="Excel workbook"/><UploadCloud className="h-10 w-10 text-brand-200"/><p className="mt-3 font-semibold">Drag and drop an Excel workbook here</p><p className="mt-1 text-sm text-muted-foreground">.xlsx or .xls · one file · maximum 10 MB</p><Button type="button" variant="secondary" className="mt-4 rounded-xl" onClick={open}>Browse Files</Button></div></CardContent>
    </Card>
    {parsing&&<div role="status" className="flex items-center gap-2 rounded-xl border border-border p-4"><Loader2 className="h-4 w-4 animate-spin"/>Validating and parsing workbook…</div>}
    {error&&<div role="alert" className="flex gap-2 rounded-xl border border-destructive/40 bg-destructive/10 p-4 text-sm text-destructive"><AlertTriangle className="h-4 w-4 shrink-0"/>{error}</div>}
    {file&&parsed&&<Card className="rounded-2xl"><CardHeader><CardTitle className="text-base">Selected workbook</CardTitle><p className="break-all text-sm font-medium">{file.name}</p><p className="text-sm text-muted-foreground">{(file.size/1024).toFixed(1)} KB · Ready to import</p></CardHeader><CardContent className="space-y-4"><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Summary label="Applicants" value={parsed.summary.applicantsFound}/><Summary label="Addresses" value={parsed.summary.addressesFound}/><Summary label="Employment" value={parsed.summary.employmentRecordsFound}/><Summary label="Assets" value={parsed.summary.assetsPopulated}/><Summary label="Liabilities" value={parsed.summary.liabilitiesPopulated}/><Summary label="Living expenses" value={parsed.summary.livingExpensesPopulated}/><Summary label="Warnings" value={parsed.summary.warnings}/></div>{parsed.warnings.length>0&&<div><p className="text-sm font-semibold">Import warnings</p><ul className="mt-1 list-disc pl-5 text-sm text-muted-foreground">{parsed.warnings.map(warning=><li key={warning}>{warning}</li>)}</ul></div>}<div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><Button type="button" variant="outline" onClick={clear}><Trash2 className="mr-2 h-4 w-4"/>Clear File</Button><Button type="button" onClick={apply}><CheckCircle2 className="mr-2 h-4 w-4"/>Review Imported Data</Button></div></CardContent></Card>}
    <AlertDialog open={confirm} onOpenChange={setConfirm}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Replace Advanced form values?</AlertDialogTitle><AlertDialogDescription>Importing this workbook will replace the current Advanced form values.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction onClick={()=>{if(parsed)onApply(parsed)}}>Import and Replace</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div>
}
function Summary({label,value}:{label:string;value:number}){return <div className="rounded-xl border border-border bg-muted/20 p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-xl font-semibold">{value}</p></div>}
