import { useMemo } from 'react';
import { useFormContext,useWatch } from 'react-hook-form';
import type { AdvancedClientCreationPayload,FactFindEmployment } from '@/lib/client-fact-find/types';
import { calculateAssetTotalsCents,calculateIncomeCents,calculateOtherLiabilitiesCents,centsToDisplay,formatNetPosition } from '@/lib/client-fact-find/calculations';
import { ASSET_LOAN_NAMES,ASSET_VALUE_NAMES,INCOME_KEYS,LIABILITY_BALANCE_NAMES,incomeNames } from './factFindWatchers';

const SUMMARY_NAMES=[...incomeNames(0),...incomeNames(1),...ASSET_VALUE_NAMES,...ASSET_LOAN_NAMES,...LIABILITY_BALANCE_NAMES] as const;
export function FactFindSummary(){const {control}=useFormContext<AdvancedClientCreationPayload>();const values=useWatch({control,name:SUMMARY_NAMES});const totals=useMemo(()=>{let offset=0;const employment=()=>Object.fromEntries(INCOME_KEYS.map(key=>[key,values[offset++]])) as Pick<FactFindEmployment,typeof INCOME_KEYS[number]>;const applicant1=employment(),applicant2=employment();const assets=ASSET_VALUE_NAMES.map((_,index)=>({currentValue:values[offset+index],loanBalance:values[offset+ASSET_VALUE_NAMES.length+index]}));offset+=ASSET_VALUE_NAMES.length+ASSET_LOAN_NAMES.length;const liabilities=LIABILITY_BALANCE_NAMES.map((_,index)=>({currentBalance:values[offset+index]}));const assetTotals=calculateAssetTotalsCents(assets);const other=calculateOtherLiabilitiesCents(liabilities);const debt=assetTotals.totalAssetLinkedDebtCents+other;return {income1:calculateIncomeCents(applicant1),income2:calculateIncomeCents(applicant2),assets:assetTotals.totalAssetsCents,debt,net:assetTotals.totalAssetsCents-debt}},[values]);return <div data-testid="fact-find-summary" className="grid grid-cols-2 gap-3 lg:grid-cols-5" aria-label="Fact find summary"><Kpi label="Applicant 1 Income" value={centsToDisplay(totals.income1)}/><Kpi label="Applicant 2 Income" value={centsToDisplay(totals.income2)}/><Kpi label="Total Assets" value={centsToDisplay(totals.assets)}/><Kpi label="Total Debt" value={centsToDisplay(totals.debt)}/><Kpi label="Net Position" value={formatNetPosition(totals.net)} negative={totals.net<0}/></div>}
function Kpi({label,value,negative=false}:{label:string;value:string;negative?:boolean}){return <div className="rounded-2xl border border-border/60 bg-card p-3"><p className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">{label}</p><p className={`mt-1 text-sm font-semibold sm:text-base ${negative?'text-destructive':'text-foreground'}`}>{value}</p></div>}
