import { useMemo } from 'react';
import { useFormContext,useWatch } from 'react-hook-form';
import type { AdvancedClientCreationPayload,FactFindEmployment } from '@/lib/client-fact-find/types';
import { calculateAssetTotalsCents,calculateIncomeCents,calculateOtherLiabilitiesCents,centsToDisplay,formatNetPosition } from '@/lib/client-fact-find/calculations';
import { ASSET_LOAN_NAMES,ASSET_VALUE_NAMES,INCOME_KEYS,LIABILITY_BALANCE_NAMES,incomeNames } from './factFindWatchers';

const SUMMARY_NAMES=[...incomeNames(0),...incomeNames(1),...ASSET_VALUE_NAMES,...ASSET_LOAN_NAMES,...LIABILITY_BALANCE_NAMES] as const;
export function FactFindSummary(){const {control}=useFormContext<AdvancedClientCreationPayload>();const values=useWatch({control,name:SUMMARY_NAMES});const totals=useMemo(()=>{let offset=0;const employment=()=>Object.fromEntries(INCOME_KEYS.map(key=>[key,values[offset++]])) as Pick<FactFindEmployment,typeof INCOME_KEYS[number]>;const applicant1=employment(),applicant2=employment();const assets=ASSET_VALUE_NAMES.map((_,index)=>({currentValue:values[offset+index],loanBalance:values[offset+ASSET_VALUE_NAMES.length+index]}));offset+=ASSET_VALUE_NAMES.length+ASSET_LOAN_NAMES.length;const liabilities=LIABILITY_BALANCE_NAMES.map((_,index)=>({currentBalance:values[offset+index]}));const assetTotals=calculateAssetTotalsCents(assets);const other=calculateOtherLiabilitiesCents(liabilities);const debt=assetTotals.totalAssetLinkedDebtCents+other;return {income1:calculateIncomeCents(applicant1),income2:calculateIncomeCents(applicant2),assets:assetTotals.totalAssetsCents,debt,net:assetTotals.totalAssetsCents-debt}},[values]);return <section data-testid="fact-find-summary" className="overflow-hidden rounded-2xl border border-border/70 bg-card shadow-sm" aria-label="Fact find summary"><div className="border-b border-border/60 bg-muted/20 px-4 py-2"><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-muted-foreground">Financial position snapshot</p></div><div className="grid grid-cols-2 lg:grid-cols-5"><Kpi label="Applicant 1 Income" value={centsToDisplay(totals.income1)}/><Kpi label="Applicant 2 Income" value={centsToDisplay(totals.income2)}/><Kpi label="Total Assets" value={centsToDisplay(totals.assets)} positive/><Kpi label="Total Debt" value={centsToDisplay(totals.debt)}/><Kpi label="Net Position" value={formatNetPosition(totals.net)} negative={totals.net<0} emphasis/></div></section>}
function Kpi({label,value,negative=false,positive=false,emphasis=false}:{label:string;value:string;negative?:boolean;positive?:boolean;emphasis?:boolean}){return <div className={`min-w-0 border-border/60 px-4 py-3.5 [&:not(:nth-child(2n+1))]:border-l lg:[&:not(:first-child)]:border-l ${emphasis?'col-span-2 bg-primary/10 lg:col-span-1':''}`}><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-muted-foreground">{label}</p><p className={`mt-1 truncate text-base font-bold tabular-nums sm:text-lg ${negative?'text-destructive':positive?'text-success':'text-foreground'}`}>{value}</p></div>}
