import { useState } from 'react';
import { UserPlus } from 'lucide-react';
import { Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle } from '@/components/ui/dialog';
import { cn } from '@/lib/utils';
import { StandardAddClientForm } from './add-client/StandardAddClientForm';
import { AdvancedClientForm } from './add-client/AdvancedClientForm';

interface AddClientModalProps { open:boolean; onOpenChange:(open:boolean)=>void }
type ClientMode='standard'|'advanced';
export function AddClientModal({open,onOpenChange}:AddClientModalProps){const [mode,setMode]=useState<ClientMode>('standard');const [session,setSession]=useState(0);const close=()=>{setMode('standard');setSession(x=>x+1);onOpenChange(false)};return <Dialog open={open} onOpenChange={isOpen=>{if(!isOpen)close();else onOpenChange(true)}}><DialogContent className={cn('flex w-[calc(100vw-1rem)] flex-col overflow-hidden border-brand-500/20 bg-background p-0 shadow-2xl transition-[max-width,height] sm:rounded-3xl',mode==='advanced'?'h-[calc(100vh-1rem)] max-h-[92vh] sm:max-w-[min(96vw,1440px)]':'max-h-[90vh] sm:max-w-[680px]')}>
 <DialogHeader className="shrink-0 border-b border-border bg-background/95 px-5 pb-3 pt-5 backdrop-blur sm:px-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><DialogTitle className="flex items-center gap-3 text-xl font-bold"><span className="flex h-10 w-10 items-center justify-center rounded-2xl border border-brand-300/25 bg-brand-300/15 text-brand-100"><UserPlus className="h-5 w-5"/></span>Add New Client</DialogTitle><DialogDescription className="mt-2">{mode==='standard'?'Create a new client record. Optionally sync to GoHighLevel.':'Review an unsaved Client Financial Position & Fact Find preview.'}</DialogDescription></div><ModeTabs mode={mode} onChange={setMode}/></div></DialogHeader>
 <div id="client-mode-panel-standard" role="tabpanel" aria-labelledby="client-mode-tab-standard" hidden={mode!=='standard'} className="min-h-0 flex-1 flex-col data-[visible=true]:flex" data-visible={mode==='standard'}><StandardAddClientForm key={`standard-${session}`} active={open&&mode==='standard'} onCancel={close} onCreated={close}/></div><div id="client-mode-panel-advanced" role="tabpanel" aria-labelledby="client-mode-tab-advanced" hidden={mode!=='advanced'} className="min-h-0 flex-1 flex-col data-[visible=true]:flex" data-visible={mode==='advanced'}><AdvancedClientForm key={`advanced-${session}`} active={open&&mode==='advanced'} onCancel={close}/></div></DialogContent></Dialog>}

function ModeTabs({mode,onChange}:{mode:ClientMode;onChange:(mode:ClientMode)=>void}){const modes:ClientMode[]=['standard','advanced'];const keyDown=(event:React.KeyboardEvent<HTMLDivElement>)=>{const current=modes.indexOf(mode);let next=current;if(event.key==='ArrowRight')next=(current+1)%modes.length;else if(event.key==='ArrowLeft')next=(current-1+modes.length)%modes.length;else if(event.key==='Home')next=0;else if(event.key==='End')next=modes.length-1;else return;event.preventDefault();onChange(modes[next]);requestAnimationFrame(()=>document.getElementById(`client-mode-tab-${modes[next]}`)?.focus())};return <div role="tablist" aria-label="Client creation mode" onKeyDown={keyDown} className="grid grid-cols-2 rounded-md bg-muted p-1">{modes.map(value=><button type="button" role="tab" id={`client-mode-tab-${value}`} aria-controls={`client-mode-panel-${value}`} aria-selected={mode===value} tabIndex={mode===value?0:-1} onClick={()=>onChange(value)} className="min-h-11 rounded-sm px-3 py-1.5 text-sm font-medium text-muted-foreground ring-offset-background transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 aria-selected:bg-background aria-selected:text-foreground aria-selected:shadow-sm sm:min-h-8" key={value}>{value==='standard'?'Standard':'Advanced'}</button>)}</div>}
