import { useState } from 'react';
import { Sparkles, UserPlus } from 'lucide-react';
import { Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle } from '@/components/ui/dialog';
import { cn } from '@/lib/utils';
import { StandardAddClientForm } from './add-client/StandardAddClientForm';
import { AdvancedClientForm } from './add-client/AdvancedClientForm';

interface AddClientModalProps { open:boolean; onOpenChange:(open:boolean)=>void }
type ClientMode='standard'|'advanced';
export function AddClientModal({open,onOpenChange}:AddClientModalProps){const [mode,setMode]=useState<ClientMode>('standard');const [session,setSession]=useState(0);const close=()=>{setMode('standard');setSession(x=>x+1);onOpenChange(false)};return <Dialog open={open} onOpenChange={isOpen=>{if(!isOpen)close();else onOpenChange(true)}}><DialogContent data-testid="add-client-modal-shell" className={cn('flex w-[calc(100vw-1rem)] flex-col gap-0 overflow-hidden p-0 transition-[max-width,height] duration-150 motion-reduce:transition-none',mode==='advanced'?'h-[min(94vh,940px)] max-h-[calc(100vh-0.75rem)] border-brand-300/35 bg-background shadow-2xl shadow-background/80 sm:max-w-[min(96vw,1480px)] sm:rounded-[1.5rem]':'max-h-[90vh] border-brand-300/25 bg-gradient-to-br from-background via-background to-muted/25 shadow-2xl shadow-foreground/20 sm:max-w-[680px] sm:rounded-[1.75rem]')}>
 <DialogHeader data-testid="add-client-premium-header" className={cn('relative shrink-0 overflow-hidden border-b px-5 py-4 text-left sm:px-6',mode==='advanced'?'border-brand-300/25 bg-gradient-to-r from-card via-background to-primary/5':'border-brand-300/20 bg-gradient-to-r from-card via-background to-brand-300/10')}><div className={cn('pointer-events-none absolute inset-x-0 top-0 h-px',mode==='advanced'?'bg-gradient-to-r from-transparent via-brand-300/70 to-transparent':'bg-transparent')}/><div className="relative flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div className="flex min-w-0 items-center gap-3"><span className={cn('dashboard-luxury-icon-tile flex h-11 w-11 shrink-0 items-center justify-center rounded-xl border',mode==='advanced'?'border-brand-300/40 bg-primary/10 shadow-inner':'shadow-lg shadow-brand-950/15')}><UserPlus className="h-5 w-5"/></span><div className="min-w-0"><DialogTitle className="text-xl font-bold tracking-tight">Add New Client</DialogTitle><DialogDescription className="mt-0.5 text-sm leading-5 text-muted-foreground">{mode==='standard'?'Create a new client record. Optionally sync to GoHighLevel.':'Review an unsaved Client Financial Position & Fact Find preview.'}</DialogDescription></div></div><ModeTabs mode={mode} onChange={setMode}/></div></DialogHeader>
 <div id="client-mode-panel-standard" role="tabpanel" aria-labelledby="client-mode-tab-standard" hidden={mode!=='standard'} className="min-h-0 flex-1 flex-col data-[visible=true]:flex" data-visible={mode==='standard'}><StandardAddClientForm key={`standard-${session}`} active={open&&mode==='standard'} onCancel={close} onCreated={close}/></div><div id="client-mode-panel-advanced" role="tabpanel" aria-labelledby="client-mode-tab-advanced" hidden={mode!=='advanced'} className="min-h-0 flex-1 flex-col data-[visible=true]:flex" data-visible={mode==='advanced'}><AdvancedClientForm key={`advanced-${session}`} active={open&&mode==='advanced'} onCancel={close}/></div></DialogContent></Dialog>}

function ModeTabs({mode,onChange}:{mode:ClientMode;onChange:(mode:ClientMode)=>void}){const modes:ClientMode[]=['standard','advanced'];const keyDown=(event:React.KeyboardEvent<HTMLDivElement>)=>{const current=modes.indexOf(mode);let next=current;if(event.key==='ArrowRight')next=(current+1)%modes.length;else if(event.key==='ArrowLeft')next=(current-1+modes.length)%modes.length;else if(event.key==='Home')next=0;else if(event.key==='End')next=modes.length-1;else return;event.preventDefault();onChange(modes[next]);requestAnimationFrame(()=>document.getElementById(`client-mode-tab-${modes[next]}`)?.focus())};return <div data-testid="premium-mode-tabs" role="tablist" aria-label="Client creation mode" onKeyDown={keyDown} className="grid shrink-0 grid-cols-2 rounded-xl border border-border/70 bg-muted/30 p-1 shadow-inner sm:min-w-64">{modes.map(value=><button type="button" role="tab" id={`client-mode-tab-${value}`} aria-controls={`client-mode-panel-${value}`} aria-selected={mode===value} tabIndex={mode===value?0:-1} onClick={()=>onChange(value)} className="flex min-h-10 items-center justify-center gap-2 rounded-lg border border-transparent px-4 text-sm font-semibold text-muted-foreground transition-[background-color,border-color,color,box-shadow,transform] duration-150 hover:bg-muted/60 hover:text-foreground active:scale-[0.98] motion-reduce:transition-none focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 aria-selected:border-brand-300/40 aria-selected:bg-primary/15 aria-selected:text-foreground aria-selected:shadow-sm" key={value}>{value==='advanced'&&<Sparkles className="h-4 w-4"/>}{value==='standard'?'Standard':'Advanced'}</button>)}</div>}
