import { useState } from 'react';
import { Sparkles, UserPlus } from 'lucide-react';
import { Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle } from '@/components/ui/dialog';
import { cn } from '@/lib/utils';
import { StandardAddClientForm } from './add-client/StandardAddClientForm';
import { AdvancedClientForm } from './add-client/AdvancedClientForm';

interface AddClientModalProps { open:boolean; onOpenChange:(open:boolean)=>void }
type ClientMode='standard'|'advanced';
export function AddClientModal({open,onOpenChange}:AddClientModalProps){const [mode,setMode]=useState<ClientMode>('standard');const [session,setSession]=useState(0);const close=()=>{setMode('standard');setSession(x=>x+1);onOpenChange(false)};return <Dialog open={open} onOpenChange={isOpen=>{if(!isOpen)close();else onOpenChange(true)}}><DialogContent data-testid="add-client-modal-shell" className={cn('flex w-[calc(100vw-1rem)] flex-col gap-0 overflow-hidden border-brand-300/25 bg-gradient-to-br from-background via-background to-muted/25 p-0 shadow-2xl shadow-foreground/20 transition-[max-width,height] sm:rounded-[1.75rem]',mode==='advanced'?'h-[min(92vh,920px)] max-h-[calc(100vh-1rem)] sm:max-w-[min(95vw,1440px)]':'max-h-[90vh] sm:max-w-[680px]')}>
 <DialogHeader data-testid="add-client-premium-header" className="relative shrink-0 overflow-hidden border-b border-brand-300/20 bg-gradient-to-r from-card via-background to-brand-300/10 px-5 py-4 text-left sm:px-6"><div className="pointer-events-none absolute -right-12 -top-16 h-40 w-40 rounded-full bg-brand-300/10 blur-3xl"/><div className="relative flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex min-w-0 items-center gap-3"><span className="dashboard-luxury-icon-tile flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl border shadow-lg shadow-brand-950/15"><UserPlus className="h-5 w-5"/></span><div className="min-w-0"><DialogTitle className="text-xl font-semibold tracking-tight">Add New Client</DialogTitle><DialogDescription className="mt-1 text-sm leading-5 text-muted-foreground">{mode==='standard'?'Create a new client record. Optionally sync to GoHighLevel.':'Review an unsaved Client Financial Position & Fact Find preview.'}</DialogDescription></div></div><ModeTabs mode={mode} onChange={setMode}/></div></DialogHeader>
 <div id="client-mode-panel-standard" role="tabpanel" aria-labelledby="client-mode-tab-standard" hidden={mode!=='standard'} className="min-h-0 flex-1 flex-col data-[visible=true]:flex" data-visible={mode==='standard'}><StandardAddClientForm key={`standard-${session}`} active={open&&mode==='standard'} onCancel={close} onCreated={close}/></div><div id="client-mode-panel-advanced" role="tabpanel" aria-labelledby="client-mode-tab-advanced" hidden={mode!=='advanced'} className="min-h-0 flex-1 flex-col data-[visible=true]:flex" data-visible={mode==='advanced'}><AdvancedClientForm key={`advanced-${session}`} active={open&&mode==='advanced'} onCancel={close}/></div></DialogContent></Dialog>}

function ModeTabs({mode,onChange}:{mode:ClientMode;onChange:(mode:ClientMode)=>void}){const modes:ClientMode[]=['standard','advanced'];const keyDown=(event:React.KeyboardEvent<HTMLDivElement>)=>{const current=modes.indexOf(mode);let next=current;if(event.key==='ArrowRight')next=(current+1)%modes.length;else if(event.key==='ArrowLeft')next=(current-1+modes.length)%modes.length;else if(event.key==='Home')next=0;else if(event.key==='End')next=modes.length-1;else return;event.preventDefault();onChange(modes[next]);requestAnimationFrame(()=>document.getElementById(`client-mode-tab-${modes[next]}`)?.focus())};return <div data-testid="premium-mode-tabs" role="tablist" aria-label="Client creation mode" onKeyDown={keyDown} className="grid shrink-0 grid-cols-2 rounded-2xl border border-border/70 bg-background/65 p-1 shadow-inner backdrop-blur sm:min-w-64">{modes.map(value=><button type="button" role="tab" id={`client-mode-tab-${value}`} aria-controls={`client-mode-panel-${value}`} aria-selected={mode===value} tabIndex={mode===value?0:-1} onClick={()=>onChange(value)} className="flex min-h-11 items-center justify-center gap-2 rounded-xl px-4 text-sm font-semibold text-muted-foreground transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 aria-selected:border aria-selected:border-brand-300/30 aria-selected:bg-brand-300/15 aria-selected:text-foreground aria-selected:shadow-md" key={value}>{value==='advanced'&&<Sparkles className="h-4 w-4"/>}{value==='standard'?'Standard':'Advanced'}</button>)}</div>}
