// GENERATED — do not edit. Run `npm run mobile:dart:tokens`.
//
// Source: mobile/design-tokens.json (itself generated from src/styles/*.css).
// Every token in that file appears here; values this generator cannot type are
// carried as raw strings so nothing is lost between web and mobile.
//
// Token counts:
//   light: 138
//   dark: 98
//   financeMidnight: 17
//   financeGraphite: 17
//
// ignore_for_file: lines_longer_than_80_chars
//
// This file's shape is owned by its generator; formatting it would make it
// disagree with the drift check, so the formatter is told to leave it alone.
// dart format off

import 'dart:ui' show Color;

/// One resolved theme's tokens, split by the Dart type each value became.
class NpcTokenSet {
  const NpcTokenSet({
    required this.name,
    required this.colors,
    required this.lengths,
    required this.durations,
    required this.raws,
  });

  final String name;
  final Map<String, Color> colors;
  final Map<String, double> lengths;
  final Map<String, Duration> durations;
  final Map<String, String> raws;

  /// Total tokens carried, across every bucket. Compared against
  /// design-tokens.json by `tokens_coverage_test.dart`.
  int get tokenCount =>
      colors.length + lengths.length + durations.length + raws.length;

  /// Every token name this set carries.
  Iterable<String> get tokenNames =>
      <String>[...colors.keys, ...lengths.keys, ...durations.keys, ...raws.keys];
}

/// The generated token tables, one per theme exported from the web app.
class NpcTokens {
  /// light — 138 tokens from design-tokens.json.
  static const NpcTokenSet light = NpcTokenSet(
    name: 'light',
    colors: <String, Color>{
      '--accent': Color(0xff8546ce),
      '--accent-foreground': Color(0xffffffff),
      '--aurixa-aurora-1': Color(0xffe6bd56),
      '--aurixa-aurora-2': Color(0xff814ddb),
      '--aurixa-aurora-3': Color(0xff1cb2fd),
      '--aurixa-glass-bg': Color(0xfffffdfa),
      '--aurixa-glass-border': Color(0xffd8cab6),
      '--aurixa-glow': Color(0xffe1b137),
      '--aurixa-hairline': Color(0xffd1c094),
      '--aurixa-obsidian': Color(0xff251f18),
      '--background': Color(0xfffaf7ef),
      '--border': Color(0xffddd1c0),
      '--border-soft': Color(0xffddd1c0),
      '--border-strong': Color(0xffcebda1),
      '--brand': Color(0xffd9a520),
      '--brand-100': Color(0xfff8eed3),
      '--brand-200': Color(0xfff3e0af),
      '--brand-300': Color(0xffecce83),
      '--brand-400': Color(0xffe6bd56),
      '--brand-50': Color(0xfffcf8ed),
      '--brand-500': Color(0xffdfac2a),
      '--brand-600': Color(0xffc8981e),
      '--brand-700': Color(0xffa98019),
      '--brand-800': Color(0xff8e6c15),
      '--brand-900': Color(0xff7c5e13),
      '--brand-950': Color(0xff4b390b),
      '--brand-foreground': Color(0xff1a1a1a),
      '--brand-light': Color(0xfffcf5e3),
      '--card': Color(0xfffffdfa),
      '--card-foreground': Color(0xff332c24),
      '--chart-1': Color(0xffd9a520),
      '--chart-10': Color(0xff719e3d),
      '--chart-2': Color(0xffd6ac51),
      '--chart-3': Color(0xff21c45d),
      '--chart-4': Color(0xffef4343),
      '--chart-5': Color(0xff7d58bb),
      '--chart-6': Color(0xffef7c2a),
      '--chart-7': Color(0xff1da595),
      '--chart-8': Color(0xffc1337a),
      '--chart-9': Color(0xff9b7617),
      '--dashboard-border-soft': Color(0xffddd1c0),
      '--dashboard-border-strong': Color(0xffcebda1),
      '--dashboard-primary-soft': Color(0xffe5def2),
      '--dashboard-primary-strong': Color(0xff6128c3),
      '--dashboard-surface': Color(0xfffffdfa),
      '--dashboard-surface-elevated': Color(0xfffcf9f3),
      '--dashboard-surface-muted': Color(0xfff2ebde),
      '--destructive': Color(0xffef4343),
      '--destructive-foreground': Color(0xffffffff),
      '--destructive-light': Color(0xfffef0f0),
      '--foreground': Color(0xff312a21),
      '--info': Color(0xff0284c5),
      '--info-foreground': Color(0xffffffff),
      '--info-light': Color(0xffebf8ff),
      '--input': Color(0xffddd1c0),
      '--mobile-nav-background': Color(0xfffffdfa),
      '--muted': Color(0xfff2ebde),
      '--muted-foreground': Color(0xff6e6253),
      '--popover': Color(0xfffffdfa),
      '--popover-foreground': Color(0xff332c24),
      '--primary': Color(0xff6128c3),
      '--primary-foreground': Color(0xffffffff),
      '--primary-hover': Color(0xff5021a1),
      '--ring': Color(0xff6128c3),
      '--secondary': Color(0xfff7f0e4),
      '--secondary-foreground': Color(0xff332c24),
      '--secondary-hover': Color(0xfff0e7d5),
      '--sidebar-accent': Color(0xff8546ce),
      '--sidebar-accent-foreground': Color(0xffffffff),
      '--sidebar-background': Color(0xfff8f2e8),
      '--sidebar-border': Color(0xffe1d6c7),
      '--sidebar-foreground': Color(0xff433a2d),
      '--sidebar-primary': Color(0xff6128c3),
      '--sidebar-primary-foreground': Color(0xffffffff),
      '--sidebar-ring': Color(0xff6128c3),
      '--sidebar-surface': Color(0xfff8f2e8),
      '--success': Color(0xff21c45d),
      '--success-foreground': Color(0xffffffff),
      '--success-light': Color(0xffe9fbf0),
      '--surface-1': Color(0xfffffdfa),
      '--surface-2': Color(0xfffcf9f3),
      '--surface-3': Color(0xfff2ebde),
      '--surface-elevated': Color(0xfffffdfa),
      '--surface-muted': Color(0xfff2ebde),
      '--topbar-background': Color(0xfffffdfa),
      '--warning': Color(0xffd9a520),
      '--warning-foreground': Color(0xffffffff),
      '--warning-light': Color(0xfffcf6e9),
    },
    lengths: <String, double>{
      '--base-font-size': 16.0,
      '--glass-blur': 16.0,
      '--glass-blur-lg': 28.0,
      '--glass-blur-sm': 8.0,
      '--glass-field-opacity': 1.0,
      '--glass-saturate': 1.5,
      '--glass-scrim-blur': 6.0,
      '--logo-height-compact': 28.0,
      '--logo-height-mobile': 32.0,
      '--logo-height-sidebar': 40.0,
      '--logo-max-width': 120.0,
      '--radius': 12.0,
      '--radius-2xl': 24.0,
      '--radius-lg': 12.0,
      '--radius-md': 8.0,
      '--radius-sm': 6.0,
      '--radius-xl': 20.0,
    },
    durations: <String, Duration>{
      '--motion-base': Duration(milliseconds: 200),
      '--motion-fast': Duration(milliseconds: 120),
      '--motion-slow': Duration(milliseconds: 320),
    },
    raws: <String, String>{
      '--aurora-gradient': 'radial-gradient( 1200px 400px at 20% -10%, hsl(var(--aurixa-aurora-1) / 0.28), transparent 60% ), radial-gradient( 800px 300px at 90% 10%, hsl(var(--aurixa-aurora-2) / 0.22), transparent 55% ), radial-gradient( 600px 220px at 50% 100%, hsl(var(--aurixa-aurora-3) / 0.18), transparent 60% )',
      '--elevation-1': '0 1px 2px 0 hsl(var(--foreground) / 0.06), 0 1px 3px 0 hsl(var(--foreground) / 0.05)',
      '--elevation-2': '0 4px 8px -2px hsl(var(--foreground) / 0.08), 0 2px 4px -2px hsl(var(--foreground) / 0.06)',
      '--elevation-3': '0 12px 24px -6px hsl(var(--foreground) / 0.12), 0 4px 8px -4px hsl(var(--foreground) / 0.08)',
      '--elevation-4': '0 24px 48px -12px hsl(var(--foreground) / 0.18), 0 8px 16px -8px hsl(var(--foreground) / 0.10)',
      '--font-heading': 'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
      '--font-mono': 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
      '--font-sans': 'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
      '--glass-field': 'radial-gradient( 46% 36% at 8% -4%, hsl(var(--aurixa-aurora-1) / 0.12), transparent 58% ), radial-gradient( 40% 32% at 94% 2%, hsl(var(--aurixa-aurora-2) / 0.10), transparent 56% ), radial-gradient( 44% 38% at 52% 104%, hsl(var(--aurixa-aurora-3) / 0.07), transparent 58% )',
      '--glass-fill': 'hsl(var(--card) / 0.58)',
      '--glass-fill-accent': 'hsl(var(--primary) / 0.10)',
      '--glass-fill-hover': 'hsl(var(--card) / 0.72)',
      '--glass-fill-raised': 'hsl(var(--popover) / 0.86)',
      '--glass-fill-strong': 'hsl(var(--card) / 0.76)',
      '--glass-fill-subtle': 'hsl(var(--card) / 0.38)',
      '--glass-hairline': 'hsl(var(--border) / 0.58)',
      '--glass-inner': 'inset 0 1px 0 0 var(--glass-specular), inset 0 -1px 0 0 hsl(var(--foreground) / 0.04)',
      '--glass-scrim': 'hsl(var(--aurixa-obsidian) / 0.34)',
      '--glass-shadow': '0 12px 34px -12px hsl(var(--foreground) / 0.20), 0 2px 8px -4px hsl(var(--foreground) / 0.10)',
      '--glass-shadow-lg': '0 28px 70px -24px hsl(var(--foreground) / 0.32), 0 8px 22px -12px hsl(var(--foreground) / 0.16)',
      '--glass-shadow-sm': '0 2px 10px -4px hsl(var(--foreground) / 0.14)',
      '--glass-sheen': 'linear-gradient( 160deg, var(--glass-specular) 0%, hsl(0 0% 100% / 0) 42%, hsl(var(--primary) / 0.05) 100% )',
      '--glass-specular': 'hsl(0 0% 100% / 0.55)',
      '--glass-specular-soft': 'hsl(0 0% 100% / 0.28)',
      '--glass-stroke': 'hsl(var(--border) / 0.58)',
      '--glass-stroke-accent': 'hsl(var(--primary) / 0.34)',
      '--glass-stroke-strong': 'hsl(var(--border) / 0.85)',
      '--glass-tint': 'hsl(var(--card) / 0.58)',
      '--motion-ease-emphasized': 'cubic-bezier(0.2, 0, 0, 1)',
      '--motion-ease-out': 'cubic-bezier(0.22, 1, 0.36, 1)',
    },
  );

  /// dark — 98 tokens from design-tokens.json.
  static const NpcTokenSet dark = NpcTokenSet(
    name: 'dark',
    colors: <String, Color>{
      '--accent': Color(0xffd9a520),
      '--accent-foreground': Color(0xff0d0d0d),
      '--aurixa-aurora-1': Color(0xffe1b137),
      '--aurixa-aurora-2': Color(0xff8756dc),
      '--aurixa-aurora-3': Color(0xff2bb7fd),
      '--aurixa-glass-bg': Color(0xff171717),
      '--aurixa-glass-border': Color(0xff50452b),
      '--aurixa-glow': Color(0xffd9a520),
      '--aurixa-hairline': Color(0xff6b5a2e),
      '--aurixa-obsidian': Color(0xff0d0d0d),
      '--background': Color(0xff0a0a0a),
      '--border': Color(0xff2e2e2e),
      '--border-soft': Color(0xff2e2e2e),
      '--border-strong': Color(0xff574e38),
      '--brand': Color(0xffd9a520),
      '--brand-foreground': Color(0xff141414),
      '--brand-light': Color(0xff3d2f0b),
      '--card': Color(0xff121212),
      '--card-foreground': Color(0xffe7e6e4),
      '--dashboard-border-soft': Color(0xff2e2e2e),
      '--dashboard-border-strong': Color(0xff574e38),
      '--dashboard-primary-soft': Color(0xff3d2f0b),
      '--dashboard-primary-strong': Color(0xffd9a520),
      '--dashboard-surface': Color(0xff121212),
      '--dashboard-surface-elevated': Color(0xff171717),
      '--dashboard-surface-muted': Color(0xff1f1f1f),
      '--destructive': Color(0xffef4343),
      '--destructive-foreground': Color(0xffffffff),
      '--destructive-light': Color(0xff3b0202),
      '--foreground': Color(0xffe7e6e4),
      '--info': Color(0xff30b9fd),
      '--info-foreground': Color(0xff0d0d0d),
      '--info-light': Color(0xff072d40),
      '--input': Color(0xff2e2e2e),
      '--mobile-nav-background': Color(0xff121212),
      '--muted': Color(0xff1f1f1f),
      '--muted-foreground': Color(0xff8c8c8c),
      '--popover': Color(0xff121212),
      '--popover-foreground': Color(0xffe7e6e4),
      '--primary': Color(0xffd9a520),
      '--primary-foreground': Color(0xff0d0d0d),
      '--primary-hover': Color(0xffba8d1c),
      '--ring': Color(0xffd9a520),
      '--secondary': Color(0xff1f1f1f),
      '--secondary-foreground': Color(0xffe7e6e4),
      '--secondary-hover': Color(0xff292929),
      '--sidebar-accent': Color(0xffd9a520),
      '--sidebar-accent-foreground': Color(0xff0d0d0d),
      '--sidebar-background': Color(0xff0f0f0f),
      '--sidebar-border': Color(0xff242424),
      '--sidebar-foreground': Color(0xffe7e6e4),
      '--sidebar-primary': Color(0xffd9a520),
      '--sidebar-primary-foreground': Color(0xff0d0d0d),
      '--sidebar-ring': Color(0xffd9a520),
      '--sidebar-surface': Color(0xff0f0f0f),
      '--success': Color(0xff21c45d),
      '--success-foreground': Color(0xffffffff),
      '--success-light': Color(0xff093419),
      '--surface-1': Color(0xff121212),
      '--surface-2': Color(0xff171717),
      '--surface-3': Color(0xff1f1f1f),
      '--surface-elevated': Color(0xff171717),
      '--surface-muted': Color(0xff1f1f1f),
      '--topbar-background': Color(0xff121212),
      '--warning': Color(0xffd9a520),
      '--warning-foreground': Color(0xff0d0d0d),
      '--warning-light': Color(0xff352808),
    },
    lengths: <String, double>{
      '--base-font-size': 16.0,
      '--glass-saturate': 1.3,
      '--logo-height-compact': 28.0,
      '--logo-height-mobile': 32.0,
      '--logo-height-sidebar': 40.0,
      '--logo-max-width': 120.0,
    },
    durations: const <String, Duration>{},
    raws: <String, String>{
      '--elevation-1': '0 1px 2px 0 hsl(0 0% 0% / 0.35), 0 1px 3px 0 hsl(0 0% 0% / 0.30)',
      '--elevation-2': '0 4px 8px -2px hsl(0 0% 0% / 0.45), 0 2px 4px -2px hsl(0 0% 0% / 0.35)',
      '--elevation-3': '0 12px 24px -6px hsl(0 0% 0% / 0.55), 0 4px 8px -4px hsl(0 0% 0% / 0.40)',
      '--elevation-4': '0 24px 48px -12px hsl(0 0% 0% / 0.65), 0 8px 16px -8px hsl(0 0% 0% / 0.45)',
      '--font-heading': 'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
      '--font-mono': 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
      '--font-sans': 'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
      '--glass-field': 'radial-gradient( 46% 36% at 8% -4%, hsl(var(--aurixa-aurora-1) / 0.10), transparent 58% ), radial-gradient( 40% 32% at 94% 2%, hsl(var(--aurixa-aurora-2) / 0.10), transparent 56% ), radial-gradient( 44% 38% at 52% 104%, hsl(var(--aurixa-aurora-3) / 0.06), transparent 58% )',
      '--glass-fill': 'hsl(var(--card) / 0.55)',
      '--glass-fill-accent': 'hsl(var(--primary) / 0.14)',
      '--glass-fill-hover': 'hsl(var(--card) / 0.70)',
      '--glass-fill-raised': 'hsl(var(--popover) / 0.84)',
      '--glass-fill-strong': 'hsl(var(--card) / 0.74)',
      '--glass-fill-subtle': 'hsl(var(--card) / 0.34)',
      '--glass-inner': 'inset 0 1px 0 0 var(--glass-specular), inset 0 -1px 0 0 hsl(0 0% 0% / 0.20)',
      '--glass-scrim': 'hsl(var(--aurixa-obsidian) / 0.62)',
      '--glass-shadow': '0 12px 34px -12px hsl(0 0% 0% / 0.62), 0 2px 8px -4px hsl(0 0% 0% / 0.40)',
      '--glass-shadow-lg': '0 28px 70px -24px hsl(0 0% 0% / 0.78), 0 8px 22px -12px hsl(0 0% 0% / 0.50)',
      '--glass-shadow-sm': '0 2px 10px -4px hsl(0 0% 0% / 0.50)',
      '--glass-sheen': 'linear-gradient( 160deg, var(--glass-specular) 0%, hsl(0 0% 100% / 0) 46%, hsl(var(--primary) / 0.06) 100% )',
      '--glass-specular': 'hsl(0 0% 100% / 0.08)',
      '--glass-specular-soft': 'hsl(0 0% 100% / 0.04)',
      '--glass-stroke': 'hsl(0 0% 100% / 0.10)',
      '--glass-stroke-accent': 'hsl(var(--primary) / 0.38)',
      '--glass-stroke-strong': 'hsl(0 0% 100% / 0.18)',
    },
  );

  /// financeMidnight — 17 tokens from design-tokens.json.
  static const NpcTokenSet financeMidnight = NpcTokenSet(
    name: 'financeMidnight',
    colors: <String, Color>{
      '--accent': Color(0xff1d3972),
      '--accent-foreground': Color(0xffe8e9ed),
      '--background': Color(0xff0b0c14),
      '--border': Color(0xff252837),
      '--card': Color(0xff11131d),
      '--card-foreground': Color(0xffe8e9ed),
      '--foreground': Color(0xffe8e9ed),
      '--input': Color(0xff252837),
      '--muted': Color(0xff1d1f2b),
      '--muted-foreground': Color(0xff9ea1b3),
      '--popover': Color(0xff11131d),
      '--popover-foreground': Color(0xffe8e9ed),
      '--primary': Color(0xff5184ec),
      '--primary-foreground': Color(0xffffffff),
      '--ring': Color(0xff5184ec),
      '--secondary': Color(0xff1d1f2b),
      '--secondary-foreground': Color(0xffe8e9ed),
    },
    lengths: const <String, double>{},
    durations: const <String, Duration>{},
    raws: const <String, String>{},
  );

  /// financeGraphite — 17 tokens from design-tokens.json.
  static const NpcTokenSet financeGraphite = NpcTokenSet(
    name: 'financeGraphite',
    colors: <String, Color>{
      '--accent': Color(0xff3a3c41),
      '--accent-foreground': Color(0xffe9eaec),
      '--background': Color(0xff121416),
      '--border': Color(0xff2f3237),
      '--card': Color(0xff191b1f),
      '--card-foreground': Color(0xffe9eaec),
      '--foreground': Color(0xffe9eaec),
      '--input': Color(0xff2f3237),
      '--muted': Color(0xff26282c),
      '--muted-foreground': Color(0xffa3a7ae),
      '--popover': Color(0xff191b1f),
      '--popover-foreground': Color(0xffe9eaec),
      '--primary': Color(0xffcbc8c2),
      '--primary-foreground': Color(0xff121416),
      '--ring': Color(0xffcbc8c2),
      '--secondary': Color(0xff26282c),
      '--secondary-foreground': Color(0xffe9eaec),
    },
    lengths: const <String, double>{},
    durations: const <String, Duration>{},
    raws: const <String, String>{},
  );

  /// Every generated theme, keyed by the name the web export used.
  static const Map<String, NpcTokenSet> all = <String, NpcTokenSet>{
    'light': light,
    'dark': dark,
    'financeMidnight': financeMidnight,
    'financeGraphite': financeGraphite,
  };
}
