/**
 * manage-partner-agreements — the Agreement Centre's Command Centre engine.
 *
 * The original register actions (list/get/create/update/transition/new_version/
 * delete_draft/effective_schedule) are unchanged in behaviour. On top of them
 * sits the digital lifecycle:
 *
 *   record_review        internal review decision (approve for issue / return)
 *   issue_to_partner     freeze a version row + put it in the partner's portal
 *   withdraw             pull an issued agreement back before execution
 *   counter_sign         the issuer's signature; finalises execution
 *   resolve_change_request  answer a partner's structured request
 *   set_owner            reassign the responsible Command Centre user
 *   duplicate_check      active/in-flight agreements for a partner (warn, not block)
 *   issuer_defaults      tenant identity for wizard prefill
 *   validate_issue       the pre-issue validation panel, server-computed
 *
 * …and disposition — the three ways an agreement leaves the working list:
 *
 *   void_agreement       declare it of no effect (reasoned, permanent, cascades)
 *   archive / restore    file it away and bring it back (reversible, no effect
 *                        on status, commission or the partner's copy)
 *   delete_agreement     destroy a row that never left the building
 *
 * Every one of those re-derives its own eligibility from the database rather
 * than trusting what the browser thought was possible, using the same pure
 * rules the UI greys the buttons out with (`lifecycle.pure.ts`).
 *
 * Authorisation: staff session + the `agreements` module, deny-by-default —
 * reads need can_view, mutations can_edit (`_shared/authz.ts`, not the
 * allow-by-default `_shared/permissions.ts`). The transition map is the shared
 * `AGREEMENT_TRANSITIONS`, so the server and both UIs agree on what is legal.
 *
 * Versioning rule: nothing externally visible is ever silently overwritten.
 * `issue_to_partner` freezes field values + brand snapshot + template content
 * hash onto a `partner_agreement_versions` row; a reissue supersedes the prior
 * row and records a field-level diff. The executed master is generated by
 * `counter_sign` and stored write-once in the `partner-agreements` bucket —
 * automatic return to the Command Centre, no manual re-upload.
 */
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { verifyAuth, createCorsHeaders, createUnauthorizedResponse, createForbiddenResponse } from '../_shared/auth.ts';
import { requireModulePermission } from '../_shared/authz.ts';
import { enforceCsrf, csrfDenied } from '../_shared/csrfGuard.ts';
import { recordPartnerAudit } from '../_shared/partnerAudit.ts';
import { insertTargetedNotification } from '../_shared/notify.ts';
import {
  AGREEMENT_TRANSITIONS,
  AGREEMENT_STATUSES,
  EDITABLE_STATUSES,
  IN_FLIGHT_STATUSES,
  agreementDeleteVerdict,
  archiveRefusal,
  canArchive,
  canVoid,
  versionLabel,
  templateKeyForDirection,
  projectFieldValues,
  validateForIssue,
  diffFieldValues,
  templateContentHash,
  agreementTemplate,
  contentOverridesFromValues,
  listAgreementAmendments,
  AGREEMENT_CENTRE_DOCUMENT_REVISION,
} from '../_shared/agreements/index.pure.ts';
import {
  captureBrandSnapshot,
  executionContextFromSignatures,
  loadIssuerDefaults,
  renderAndStoreVersionPdf,
} from '../_shared/agreements/render.ts';

const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;

const TABLE = 'partner_agreements';
const EVENTS_TABLE = 'partner_agreement_events';
const VERSIONS_TABLE = 'partner_agreement_versions';
const REVIEWS_TABLE = 'partner_agreement_reviews';
const CHANGE_REQUESTS_TABLE = 'partner_agreement_change_requests';
const SIGNATURES_TABLE = 'partner_agreement_signatures';

const DIRECTIONS = new Set(['inbound_property_referral', 'outbound_finance_referral']);
const STATUSES = new Set<string>(AGREEMENT_STATUSES);

/** Long enough that "n/a" does not satisfy the void audit trail. */
const MIN_VOID_REASON = 6;

/**
 * `verifyAuth` reports an internal caller as the literal string
 * `'service_role'`, and every "who did this" column here is a UUID. Writing
 * the string into one does not fail a type check anywhere — it fails in
 * Postgres, at the moment of the write, with `invalid input syntax for type
 * uuid`, taking the whole action down with it.
 *
 * Two call sites already spelled this guard out inline. It is a function now
 * because the disposition actions added more, and a rule enforced by
 * remembering is not enforced.
 */
function staffId(actorId: string | null): string | null {
  return !actorId || actorId === 'service_role' ? null : actorId;
}

/** Status transitions permitted by the agreement engine — shared with the UIs. */
const TRANSITIONS: Record<string, string[]> = AGREEMENT_TRANSITIONS;

/** Columns a caller may write. Anything else is ignored (never trusted from the client). */
const WRITABLE_FIELDS = [
  'direction', 'document_version', 'finance_agent_contact_id',
  'partner_legal_name', 'partner_trading_name', 'partner_abn', 'partner_acn',
  'partner_acl_number', 'partner_credit_rep_number', 'partner_aggregator',
  'partner_address', 'partner_contact_name', 'partner_contact_email',
  'partner_contact_phone', 'partner_notice_email',
  'principal_legal_name', 'principal_trading_name', 'principal_abn', 'principal_acn',
  'principal_licence_number', 'principal_address', 'principal_contact_name',
  'principal_contact_email', 'principal_notice_email',
  'governing_state', 'effective_date', 'termination_date', 'termination_notice_days',
  'dispute_window_days', 'records_retention_years', 'executed_under_s127',
  'fee_model', 'fee_amount', 'fee_percentage', 'gst_treatment', 'qualifying_event',
  'payment_business_days', 'invoice_process', 'exclusions', 'duplicate_referral_rule',
  'fee_cap', 'fee_minimum', 'post_termination_entitlement',
  'upfront_share_pct', 'trail_share_pct', 'commission_basis', 'payment_cycle',
  'cleared_funds_required', 'clawback_treatment', 'clawback_repayment_days',
  'includes_refinance_topup', 'schedule_extras',
  'template_id', 'sent_via', 'notes',
] as const;

const NUMERIC_FIELDS = new Set([
  'fee_amount', 'fee_percentage', 'fee_cap', 'fee_minimum',
  'upfront_share_pct', 'trail_share_pct',
]);
const INT_FIELDS = new Set([
  'payment_business_days', 'termination_notice_days', 'dispute_window_days',
  'records_retention_years', 'clawback_repayment_days',
]);
const DATE_FIELDS = new Set(['effective_date', 'termination_date']);

/**
 * Copy only the columns in `WRITABLE_FIELDS`, dropping everything else the
 * caller sent.
 *
 * Named for what it does rather than `sanitize`, which claimed something had
 * been cleaned without saying against what — and left the allowlist invisible at
 * the call site, where it is the only thing standing between a request body and
 * every column of the table.
 */
function pickWritable(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const key of WRITABLE_FIELDS) {
    if (!(key in input)) continue;
    let value = input[key as string];
    if (value === '' || value === undefined) value = null;
    if (value !== null && NUMERIC_FIELDS.has(key)) {
      const n = Number(value);
      value = Number.isFinite(n) ? n : null;
    }
    if (value !== null && INT_FIELDS.has(key)) {
      const n = parseInt(String(value), 10);
      value = Number.isFinite(n) ? n : null;
    }
    if (value !== null && DATE_FIELDS.has(key)) {
      value = String(value).slice(0, 10);
    }
    out[key] = value;
  }
  return out;
}

function json(body: unknown, corsHeaders: Record<string, string>, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  });
}

async function logEvent(
  supabase: any,
  agreementId: string,
  eventType: string,
  actorId: string | null,
  actorLabel: string | null,
  summary: string,
  payload: Record<string, unknown> = {},
) {
  const { error } = await supabase.from(EVENTS_TABLE).insert({
    agreement_id: agreementId,
    event_type: eventType,
    actor_id: staffId(actorId),
    actor_label: actorLabel,
    summary,
    payload,
  });
  if (error) console.error('[partner-agreements] event log failed:', error.message);

  // Phase 6 — mirror into the tamper-evident compliance chain.
  await recordPartnerAudit(supabase, {
    agreement_id: agreementId,
    scope_type: 'agreement',
    scope_id: agreementId,
    actor_id: staffId(actorId),
    actor_label: actorLabel,
    severity: eventType === 'terminated' || eventType === 'void' ? 'critical' : 'info',
    category: 'lifecycle',
    action: `agreement_${eventType}`,
    target_type: 'partner_agreement',
    target_id: agreementId,
    description: summary,
    metadata: payload,
  });
}

/** In-app notification to the partner org's portal login, if it has one. */
async function notifyPartner(
  supabase: any,
  financeContactId: string | null | undefined,
  notification: { type: string; title: string; body: string; link: string; agreementId: string },
) {
  try {
    if (!financeContactId) return;
    const { data: portalUser } = await supabase
      .from('finance_portal_users')
      .select('id')
      .eq('finance_contact_id', financeContactId)
      .eq('is_active', true)
      .maybeSingle();
    if (!portalUser?.id) return;
    await supabase.from('finance_portal_notifications').insert({
      portal_user_id: portalUser.id,
      client_id: null,
      notification_type: notification.type,
      title: notification.title,
      body: notification.body,
      link_path: notification.link,
      metadata: { agreement_id: notification.agreementId, origin_portal: 'command_center' },
    });
  } catch (e) {
    // Notification delivery must never break the lifecycle action.
    console.error('[partner-agreements] partner notify failed:', e);
  }
}

/** The current issued version row, or null. */
async function currentVersion(supabase: any, agreement: any) {
  if (!agreement.issued_version_id) return null;
  const { data } = await supabase
    .from(VERSIONS_TABLE).select('*').eq('id', agreement.issued_version_id).maybeSingle();
  return data ?? null;
}

Deno.serve(async (req) => {
  const origin = req.headers.get('origin');
  const corsHeaders = createCorsHeaders(origin);

  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  const csrf = enforceCsrf(req);
  if (!csrf.ok) return csrfDenied(corsHeaders, csrf);

  try {
    const supabase = createClient(supabaseUrl, supabaseServiceKey);
    const body = await req.json();

    const authResult = await verifyAuth(supabase, req.headers, body);
    if (authResult.error) {
      return createUnauthorizedResponse(authResult.error, corsHeaders);
    }
    const actorId = authResult.userId ?? null;
    const actorLabel = authResult.username ?? null;

    const { action } = body;

    // Deny-by-default module gate. Reads need view; anything that changes a
    // row, a status or a document needs edit.
    const READ_ACTIONS = new Set([
      'list', 'get', 'list_partners', 'effective_schedule', 'duplicate_check',
      'issuer_defaults', 'validate_issue',
    ]);
    const authz = await requireModulePermission(
      supabase,
      { userId: authResult.userId, authMethod: authResult.authMethod },
      'agreements',
      READ_ACTIONS.has(action) ? 'can_view' : 'can_edit',
    );
    if (!authz.ok) return createForbiddenResponse(authz.error || 'Not authorized', corsHeaders);

    // An archived agreement is out of the working list, so work on it is work
    // nobody can see. Restoring first is one click and makes the row visible
    // to the next person who wonders why it moved. Deletion and restore are
    // the exceptions — both are how an archived row legitimately leaves.
    const ARCHIVE_BLOCKED_ACTIONS = new Set([
      'update', 'transition', 'record_review', 'issue_to_partner', 'withdraw',
      'counter_sign', 'resolve_change_request', 'new_version', 'void_agreement',
    ]);
    if (ARCHIVE_BLOCKED_ACTIONS.has(action) && typeof body.id === 'string' && body.id) {
      const { data: archiveCheck } = await supabase
        .from(TABLE).select('archived_at').eq('id', body.id).maybeSingle();
      if (archiveCheck?.archived_at) {
        return json({
          error: 'agreement_archived',
          message: 'This agreement is archived. Restore it to the working list before changing it.',
        }, corsHeaders, 409);
      }
    }

    // ─── LIST ───────────────────────────────────────────────
    if (action === 'list') {
      let query = supabase.from(TABLE).select('*').order('created_at', { ascending: false });
      if (body.direction && DIRECTIONS.has(body.direction)) query = query.eq('direction', body.direction);
      if (body.status && STATUSES.has(body.status)) query = query.eq('status', body.status);
      if (body.finance_agent_contact_id) query = query.eq('finance_agent_contact_id', body.finance_agent_contact_id);

      // The working list excludes the archive by default — that is the whole
      // point of archiving. `only` is the archive view, `all` is for anything
      // that must not be fooled by a filing decision.
      const archived = body.archived === 'only' || body.archived === 'all' ? body.archived : 'exclude';
      if (archived === 'exclude') query = query.is('archived_at', null);
      if (archived === 'only') query = query.not('archived_at', 'is', null);

      const { data, error } = await query;
      if (error) throw error;

      // The archived count travels with the working list so the UI can offer
      // the archive without a second round trip — and so a user who archived
      // something can see where it went.
      const { count: archivedCount } = await supabase
        .from(TABLE).select('id', { count: 'exact', head: true })
        .not('archived_at', 'is', null);

      return json({ agreements: data ?? [], archived_count: archivedCount ?? 0 }, corsHeaders);
    }

    // ─── GET (with events, versions, reviews, change requests, signatures) ──
    if (action === 'get') {
      const { id } = body;
      if (!id) return json({ error: 'id_required' }, corsHeaders, 400);

      const { data: agreement, error } = await supabase.from(TABLE).select('*').eq('id', id).maybeSingle();
      if (error) throw error;
      if (!agreement) return json({ error: 'not_found' }, corsHeaders, 404);

      const [events, rowChain, versions, reviews, changeRequests, signatures] = await Promise.all([
        supabase.from(EVENTS_TABLE).select('*').eq('agreement_id', id)
          .order('created_at', { ascending: false }).limit(200),
        supabase.from(TABLE)
          .select('id, version, status, effective_date, created_at, supersedes_agreement_id')
          .or(`id.eq.${id},supersedes_agreement_id.eq.${id}`)
          .order('version', { ascending: false }),
        supabase.from(VERSIONS_TABLE)
          .select('id, version_label, issue_sequence, status, issued_at, issued_by_label, changed_fields, template_content_hash, pdf_storage_path, executed_pdf_storage_path, executed_at')
          .eq('agreement_id', id).order('issue_sequence', { ascending: false }),
        supabase.from(REVIEWS_TABLE).select('*').eq('agreement_id', id)
          .order('created_at', { ascending: false }).limit(50),
        supabase.from(CHANGE_REQUESTS_TABLE).select('*').eq('agreement_id', id)
          .order('created_at', { ascending: false }).limit(100),
        supabase.from(SIGNATURES_TABLE)
          .select('id, version_id, party_role, legal_entity, signatory_name, signatory_title, signature_method, signed_at')
          .eq('agreement_id', id).order('signed_at', { ascending: true }),
      ]);

      return json({
        agreement,
        events: events.data ?? [],
        versions: rowChain.data ?? [],
        issued_versions: versions.data ?? [],
        reviews: reviews.data ?? [],
        change_requests: changeRequests.data ?? [],
        signatures: signatures.data ?? [],
        document_revision: AGREEMENT_CENTRE_DOCUMENT_REVISION,
      }, corsHeaders);
    }

    // ─── PARTNER PICKER (finance partner contacts) ──────────
    if (action === 'list_partners') {
      // The REAL columns. This select used to name `company_name`,
      // `contact_name` and `phone` — columns `finance_agent_contacts` has
      // never had (they are `company`, `name`, and nothing) — so PostgREST
      // errored and every partner picker built on this action showed an empty
      // list. The response keeps the old field names as a projection so
      // existing callers are unaffected.
      const { data, error } = await supabase
        .from('finance_agent_contacts')
        .select('id, name, email, company, abn, is_active, gst_registered, default_commission_rate_pct, default_commission_basis')
        .eq('is_active', true)
        .order('company', { ascending: true, nullsFirst: false });
      if (error) throw error;

      // Which partners can actually receive a digital issue — an active portal
      // login. Surfaced up front so the wizard says so before step 8, not after.
      const { data: portalUsers } = await supabase
        .from('finance_portal_users')
        .select('finance_contact_id')
        .eq('is_active', true);
      const connected = new Set((portalUsers ?? []).map((u: any) => u.finance_contact_id));

      return json({
        partners: (data ?? []).map((partner: any) => ({
          id: partner.id,
          company_name: partner.company ?? null,
          contact_name: partner.name ?? null,
          email: partner.email ?? null,
          phone: null,
          abn: partner.abn ?? null,
          gst_registered: partner.gst_registered ?? null,
          default_commission_rate_pct: partner.default_commission_rate_pct ?? null,
          default_commission_basis: partner.default_commission_basis ?? null,
          portal_connected: connected.has(partner.id),
        })),
      }, corsHeaders);
    }

    // ─── CREATE PARTNER (inline, from the wizard) ───────────
    if (action === 'create_partner') {
      const companyName = String(body.company_name ?? '').trim();
      const contactName = String(body.contact_name ?? '').trim();
      const email = String(body.email ?? '').trim();
      const abn = String(body.abn ?? '').trim();
      if (!companyName && !contactName) {
        return json({ error: 'partner_name_required', message: 'A company or contact name is required.' }, corsHeaders, 422);
      }
      if (!email) {
        return json({ error: 'email_required', message: 'An email address is required for the partner record.' }, corsHeaders, 422);
      }

      const { data, error } = await supabase
        .from('finance_agent_contacts')
        .insert({
          name: contactName || companyName,
          company: companyName || null,
          email,
          abn: abn || null,
          contact_type: 'external',
          is_active: true,
          created_by: staffId(actorId),
        })
        .select('id, name, email, company, abn')
        .single();
      if (error) throw error;

      return json({
        partner: {
          id: data.id,
          company_name: data.company ?? null,
          contact_name: data.name ?? null,
          email: data.email ?? null,
          phone: null,
          abn: data.abn ?? null,
          portal_connected: false,
        },
      }, corsHeaders);
    }

    // ─── ISSUER DEFAULTS (wizard prefill) ───────────────────
    if (action === 'issuer_defaults') {
      const defaults = await loadIssuerDefaults(supabase);
      return json({ issuer: defaults }, corsHeaders);
    }

    // ─── DUPLICATE CHECK (warn, never block) ────────────────
    // Deliberately blind to `archived_at`: an archived agreement that is still
    // live is still a duplicate, and a warning that a tidy-up can switch off
    // is not a warning.
    if (action === 'duplicate_check') {
      const { finance_agent_contact_id, direction } = body;
      if (!finance_agent_contact_id) return json({ agreements: [] }, corsHeaders);
      let query = supabase.from(TABLE)
        .select('id, direction, status, version, effective_date, partner_legal_name, created_at')
        .eq('finance_agent_contact_id', finance_agent_contact_id)
        .in('status', IN_FLIGHT_STATUSES as unknown as string[]);
      if (direction && DIRECTIONS.has(direction)) query = query.eq('direction', direction);
      const { data, error } = await query;
      if (error) throw error;
      return json({ agreements: data ?? [] }, corsHeaders);
    }

    // ─── VALIDATE (the pre-issue panel, server-computed) ────
    if (action === 'validate_issue') {
      const { id } = body;
      if (!id) return json({ error: 'id_required' }, corsHeaders, 400);
      const { data: agreement } = await supabase.from(TABLE).select('*').eq('id', id).maybeSingle();
      if (!agreement) return json({ error: 'not_found' }, corsHeaders, 404);
      const templateKey = templateKeyForDirection(agreement.direction);
      const values = projectFieldValues(templateKey, agreement);
      const validation = validateForIssue(templateKey, values);

      // A digital issue additionally needs a partner record with portal access.
      const issues: { key: string; label: string; sectionId: string }[] = [...validation.missing];
      if (!agreement.finance_agent_contact_id) {
        issues.push({ key: 'finance_agent_contact_id', label: 'Linked finance partner record', sectionId: 'agreement_details' });
      }
      return json({ ok: issues.length === 0, missing: issues }, corsHeaders);
    }

    // ─── CREATE ─────────────────────────────────────────────
    if (action === 'create') {
      const payload = pickWritable(body);
      if (!payload.direction || !DIRECTIONS.has(String(payload.direction))) {
        return json({ error: 'direction_invalid' }, corsHeaders, 400);
      }
      if (!payload.partner_legal_name) {
        return json({ error: 'partner_legal_name_required' }, corsHeaders, 400);
      }

      const { data, error } = await supabase
        .from(TABLE)
        .insert({
          ...payload,
          status: 'draft',
          version: 1,
          created_by: staffId(actorId),
          updated_by: staffId(actorId),
          agreement_owner_id: staffId(actorId),
          agreement_owner_label: actorLabel,
        })
        .select()
        .single();
      if (error) throw error;

      await logEvent(supabase, data.id, 'created', actorId, actorLabel,
        `Draft agreement created (${data.direction})`, { direction: data.direction });

      return json({ agreement: data }, corsHeaders);
    }

    // ─── UPDATE (draft-stage editing + schedule editing) ────
    if (action === 'update') {
      const { id } = body;
      if (!id) return json({ error: 'id_required' }, corsHeaders, 400);

      const { data: existing, error: fetchErr } = await supabase
        .from(TABLE).select('*').eq('id', id).maybeSingle();
      if (fetchErr) throw fetchErr;
      if (!existing) return json({ error: 'not_found' }, corsHeaders, 404);

      if (['terminated', 'superseded', 'void'].includes(existing.status)) {
        return json({ error: 'agreement_locked', message: 'Terminated, superseded and void agreements are immutable. Create a new version instead.' }, corsHeaders, 409);
      }
      if (existing.status === 'active') {
        return json({ error: 'agreement_active', message: 'Active agreements cannot be edited in place. Create a new version to vary the terms.' }, corsHeaders, 409);
      }
      if (!EDITABLE_STATUSES.includes(existing.status)) {
        return json({
          error: 'agreement_issued',
          message: 'This version is in front of the partner. Move it back to draft (revise) to change it — the issued version stays on record.',
        }, corsHeaders, 409);
      }

      const payload = pickWritable(body);
      delete payload.direction; // direction is immutable once created
      const changedKeys = Object.keys(payload).filter((k) => String(existing[k] ?? '') !== String(payload[k] ?? ''));

      const { data, error } = await supabase
        .from(TABLE)
        .update({ ...payload, updated_by: staffId(actorId) })
        .eq('id', id)
        .select()
        .single();
      if (error) throw error;

      if (changedKeys.length > 0) {
        await logEvent(supabase, id, 'updated', actorId, actorLabel,
          `Updated ${changedKeys.length} field(s)`, { fields: changedKeys });
      }

      return json({ agreement: data }, corsHeaders);
    }

    // ─── TRANSITION STATUS ──────────────────────────────────
    if (action === 'transition') {
      const { id, status: nextStatus, reason } = body;
      if (!id) return json({ error: 'id_required' }, corsHeaders, 400);
      if (!STATUSES.has(nextStatus)) return json({ error: 'status_invalid' }, corsHeaders, 400);

      const { data: existing, error: fetchErr } = await supabase
        .from(TABLE).select('*').eq('id', id).maybeSingle();
      if (fetchErr) throw fetchErr;
      if (!existing) return json({ error: 'not_found' }, corsHeaders, 404);

      const allowed = TRANSITIONS[existing.status] ?? [];
      if (!allowed.includes(nextStatus)) {
        return json({
          error: 'transition_not_allowed',
          message: `Cannot move an agreement from "${existing.status}" to "${nextStatus}".`,
        }, corsHeaders, 409);
      }

      // Issuing and counter-signing have their own actions with their own
      // side-effects; the generic transition must not bypass them.
      if (nextStatus === 'partner_review') {
        return json({ error: 'use_issue_action', message: 'Use the Issue to Partner action to send an agreement to the portal.' }, corsHeaders, 409);
      }
      // Voiding requires a reason, cascades to the issued version rows and
      // tells the partner. A generic status flip does none of that, and used
      // to write its reason into `termination_reason` — the wrong column.
      if (nextStatus === 'void') {
        return json({ error: 'use_void_action', message: 'Use the Void action, which records why and notifies the partner.' }, corsHeaders, 409);
      }

      // Activation gate — a live agreement must carry executable commercial terms.
      if (nextStatus === 'active') {
        const missing: string[] = [];
        if (!existing.effective_date) missing.push('Effective date');
        if (!existing.governing_state) missing.push('Governing state');
        if (!existing.qualifying_event) missing.push('Qualifying event');
        if (!existing.gst_treatment) missing.push('GST treatment');
        if (existing.direction === 'inbound_property_referral') {
          if (!existing.fee_model) missing.push('Remuneration model');
          if (existing.fee_model === 'fixed_fee' && existing.fee_amount == null) missing.push('Fee amount');
          if (existing.fee_model === 'percentage_of_fee' && existing.fee_percentage == null) missing.push('Fee percentage');
        } else {
          if (existing.upfront_share_pct == null) missing.push('Upfront commission share');
          if (!existing.commission_basis) missing.push('Commission basis');
        }
        if (missing.length > 0) {
          return json({ error: 'schedule_incomplete', message: `Complete the commercial schedule first: ${missing.join(', ')}.`, missing }, corsHeaders, 422);
        }
      }

      const patch: Record<string, unknown> = { status: nextStatus, updated_by: staffId(actorId) };
      if (nextStatus === 'active') patch.activated_at = new Date().toISOString();
      if (nextStatus === 'sent_for_signature' && existing.status !== 'partner_review') {
        patch.docusign_sent_at = new Date().toISOString();
      }
      if (nextStatus === 'terminated') {
        patch.terminated_at = new Date().toISOString();
        patch.termination_reason = reason ?? null;
        patch.termination_date = body.termination_date ?? new Date().toISOString().slice(0, 10);
      }

      const { data, error } = await supabase.from(TABLE).update(patch).eq('id', id).select().single();
      if (error) throw error;

      await logEvent(supabase, id, `status_${nextStatus}`, actorId, actorLabel,
        `Status changed ${existing.status} → ${nextStatus}`, { from: existing.status, to: nextStatus, reason: reason ?? null });

      return json({ agreement: data }, corsHeaders);
    }

    // ─── INTERNAL REVIEW DECISION ───────────────────────────
    if (action === 'record_review') {
      const { id, decision, notes } = body;
      if (!id) return json({ error: 'id_required' }, corsHeaders, 400);
      if (decision !== 'approved' && decision !== 'returned') {
        return json({ error: 'decision_invalid' }, corsHeaders, 400);
      }

      const { data: existing } = await supabase.from(TABLE).select('*').eq('id', id).maybeSingle();
      if (!existing) return json({ error: 'not_found' }, corsHeaders, 404);
      if (existing.status !== 'pending_review') {
        return json({ error: 'not_in_review', message: 'Only agreements in Internal Review can be decided.' }, corsHeaders, 409);
      }

      if (decision === 'approved') {
        // The approval IS the pre-issue gate: an incomplete agreement cannot
        // become "Ready to Issue" no matter what the browser showed.
        const templateKey = templateKeyForDirection(existing.direction);
        const validation = validateForIssue(templateKey, projectFieldValues(templateKey, existing));
        if (!validation.ok) {
          return json({
            error: 'validation_failed',
            message: `${validation.missing.length} item(s) require attention before issue.`,
            missing: validation.missing,
          }, corsHeaders, 422);
        }
      }

      const nextStatus = decision === 'approved' ? 'approved_for_issue' : 'draft';
      const { data, error } = await supabase.from(TABLE)
        .update({ status: nextStatus, updated_by: staffId(actorId) })
        .eq('id', id).eq('status', 'pending_review')
        .select().single();
      if (error) throw error;

      await supabase.from(REVIEWS_TABLE).insert({
        agreement_id: id,
        decision,
        reviewer_id: staffId(actorId),
        reviewer_label: actorLabel,
        notes: notes ?? null,
      });

      await logEvent(supabase, id, decision === 'approved' ? 'review_approved' : 'review_returned',
        actorId, actorLabel,
        decision === 'approved' ? 'Internal review completed — approved for issue' : 'Internal review returned the agreement to draft',
        { notes: notes ?? null });

      return json({ agreement: data }, corsHeaders);
    }

    // ─── ISSUE TO FINANCE PARTNER PORTAL ────────────────────
    if (action === 'issue_to_partner') {
      const { id } = body;
      if (!id) return json({ error: 'id_required' }, corsHeaders, 400);

      const { data: existing } = await supabase.from(TABLE).select('*').eq('id', id).maybeSingle();
      if (!existing) return json({ error: 'not_found' }, corsHeaders, 404);
      if (existing.status !== 'approved_for_issue') {
        return json({ error: 'not_approved', message: 'Approve the agreement internally before issuing it.' }, corsHeaders, 409);
      }
      if (!existing.finance_agent_contact_id) {
        return json({ error: 'partner_not_linked', message: 'Link a finance partner record before issuing.' }, corsHeaders, 422);
      }

      const { data: portalUser } = await supabase
        .from('finance_portal_users')
        .select('id, email')
        .eq('finance_contact_id', existing.finance_agent_contact_id)
        .eq('is_active', true)
        .maybeSingle();
      if (!portalUser?.id) {
        return json({
          error: 'partner_portal_not_connected',
          message: 'This partner has no active Finance Portal login. Invite them to the portal first, or use the download options instead.',
        }, corsHeaders, 422);
      }

      // Server-side validation again at the boundary that matters most.
      const templateKey = templateKeyForDirection(existing.direction);
      const values = projectFieldValues(templateKey, existing);
      const validation = validateForIssue(templateKey, values);
      if (!validation.ok) {
        return json({
          error: 'validation_failed',
          message: `${validation.missing.length} item(s) require attention before issue.`,
          missing: validation.missing,
        }, corsHeaders, 422);
      }

      // Freeze the version. Brand snapshot comes from the same fetch every
      // report render uses, then lives on the version row for reproducibility.
      const snapshot = await captureBrandSnapshot(supabase, supabaseUrl);

      const { count } = await supabase.from(VERSIONS_TABLE)
        .select('id', { count: 'exact', head: true })
        .eq('agreement_id', id);
      const issueSequence = (count ?? 0) + 1;
      const label = versionLabel(existing.version ?? 1, issueSequence);

      // What changed since the version the partner last saw — UI metadata for
      // the "Updated in Version 1.1" summary.
      let changedFields: unknown[] = [];
      const { data: previous } = await supabase.from(VERSIONS_TABLE)
        .select('id, field_values')
        .eq('agreement_id', id)
        .order('issue_sequence', { ascending: false })
        .limit(1)
        .maybeSingle();
      if (previous?.field_values) {
        changedFields = diffFieldValues(templateKey, previous.field_values, values);
      }

      const { data: version, error: versionError } = await supabase.from(VERSIONS_TABLE).insert({
        agreement_id: id,
        version_label: label,
        issue_sequence: issueSequence,
        template_key: templateKey,
        template_content_hash: templateContentHash(templateKey),
        document_revision: AGREEMENT_CENTRE_DOCUMENT_REVISION,
        field_values: values,
        brand_snapshot: snapshot,
        changed_fields: changedFields,
        status: 'issued',
        issued_by: staffId(actorId),
        issued_by_label: actorLabel,
      }).select().single();
      if (versionError) throw versionError;

      // Prior issued versions are superseded — never deleted, never edited.
      if (previous?.id) {
        await supabase.from(VERSIONS_TABLE)
          .update({ status: 'superseded' })
          .eq('agreement_id', id)
          .eq('status', 'issued')
          .neq('id', version.id);
      }

      const { data: updated, error: updateError } = await supabase.from(TABLE).update({
        status: 'partner_review',
        issued_at: new Date().toISOString(),
        issued_version_id: version.id,
        sent_via: 'partner_portal',
        updated_by: staffId(actorId),
      }).eq('id', id).eq('status', 'approved_for_issue').select().single();
      if (updateError) throw updateError;

      // Open change requests answered by this reissue.
      await supabase.from(CHANGE_REQUESTS_TABLE)
        .update({
          status: 'resolved',
          resolved_in_version_id: version.id,
          resolved_by: staffId(actorId),
          resolved_by_label: actorLabel,
          resolved_at: new Date().toISOString(),
          resolution_note: `Addressed in version ${label}`,
        })
        .eq('agreement_id', id)
        .eq('status', 'open');

      await logEvent(supabase, id, issueSequence === 1 ? 'issued' : 'reissued', actorId, actorLabel,
        `Version ${label} issued to ${existing.partner_legal_name}`,
        {
          version_id: version.id,
          version_label: label,
          changed_fields: changedFields,
          // A negotiated wording change is a compliance fact, not a styling
          // choice — the audit trail records how many clauses this version
          // amends and which ones, alongside the field diff.
          amendments: listAgreementAmendments(
            agreementTemplate(templateKey),
            contentOverridesFromValues(values),
          ).map((amendment) => ({ path: amendment.path, label: amendment.label })),
        });

      const template = agreementTemplate(templateKey);
      await notifyPartner(supabase, existing.finance_agent_contact_id, {
        type: issueSequence === 1 ? 'agreement_issued' : 'agreement_reissued',
        title: issueSequence === 1 ? 'New agreement for review' : 'Updated agreement available',
        body: `${template.title} (version ${label}) is ready for your review.`,
        link: `/finance/agreements/${id}`,
        agreementId: id,
      });

      // The as-issued PDF. Best-effort: a renderer outage must not block the
      // issue — the partner's first download generates it instead.
      try {
        const stored = await renderAndStoreVersionPdf(supabase, supabaseUrl, updated, version, 'issued');
        await supabase.from(VERSIONS_TABLE).update({ pdf_storage_path: stored.path }).eq('id', version.id);
      } catch (e) {
        console.warn('[partner-agreements] issued PDF deferred to first download:', e instanceof Error ? e.message : e);
      }

      return json({ agreement: updated, version }, corsHeaders);
    }

    // ─── WITHDRAW (before execution) ────────────────────────
    if (action === 'withdraw') {
      const { id, reason } = body;
      if (!id) return json({ error: 'id_required' }, corsHeaders, 400);

      const { data: existing } = await supabase.from(TABLE).select('*').eq('id', id).maybeSingle();
      if (!existing) return json({ error: 'not_found' }, corsHeaders, 404);
      if (!(TRANSITIONS[existing.status] ?? []).includes('withdrawn')) {
        return json({ error: 'transition_not_allowed', message: `An agreement in "${existing.status}" cannot be withdrawn.` }, corsHeaders, 409);
      }

      const { data, error } = await supabase.from(TABLE).update({
        status: 'withdrawn',
        withdrawn_at: new Date().toISOString(),
        updated_by: staffId(actorId),
      }).eq('id', id).select().single();
      if (error) throw error;

      if (existing.issued_version_id) {
        await supabase.from(VERSIONS_TABLE)
          .update({ status: 'withdrawn' })
          .eq('id', existing.issued_version_id)
          .eq('status', 'issued');
      }

      await logEvent(supabase, id, 'withdrawn', actorId, actorLabel,
        `Agreement withdrawn${reason ? ` — ${reason}` : ''}`, { reason: reason ?? null });

      await notifyPartner(supabase, existing.finance_agent_contact_id, {
        type: 'agreement_withdrawn',
        title: 'Agreement withdrawn',
        body: 'The issuing organisation has withdrawn this agreement. It is no longer available for execution.',
        link: `/finance/agreements/${id}`,
        agreementId: id,
      });

      return json({ agreement: data }, corsHeaders);
    }

    // ─── COUNTER-SIGN (finalises execution) ─────────────────
    if (action === 'counter_sign') {
      const { id, signatory_name, signatory_title, signature_typed } = body;
      if (!id) return json({ error: 'id_required' }, corsHeaders, 400);
      if (!signatory_name || !signature_typed) {
        return json({ error: 'signature_required', message: 'Signatory name and a typed signature are required.' }, corsHeaders, 422);
      }

      const { data: existing } = await supabase.from(TABLE).select('*').eq('id', id).maybeSingle();
      if (!existing) return json({ error: 'not_found' }, corsHeaders, 404);
      if (existing.status !== 'partially_signed') {
        return json({ error: 'not_ready', message: 'The partner must sign before the agreement can be counter-signed.' }, corsHeaders, 409);
      }
      const version = await currentVersion(supabase, existing);
      if (!version) return json({ error: 'version_missing' }, corsHeaders, 409);

      const { data: partnerSignature } = await supabase.from(SIGNATURES_TABLE)
        .select('*').eq('version_id', version.id).eq('party_role', 'partner').maybeSingle();
      if (!partnerSignature) {
        return json({ error: 'partner_signature_missing' }, corsHeaders, 409);
      }

      const { error: signatureError } = await supabase.from(SIGNATURES_TABLE).insert({
        agreement_id: id,
        version_id: version.id,
        party_role: 'principal',
        legal_entity: existing.principal_legal_name,
        signatory_name,
        signatory_title: signatory_title ?? null,
        signature_typed,
        signature_method: 'typed_electronic',
        staff_user_id: staffId(actorId),
      });
      if (signatureError) {
        if (/duplicate|unique/i.test(signatureError.message)) {
          return json({ error: 'already_signed', message: 'This version already carries the issuer signature.' }, corsHeaders, 409);
        }
        throw signatureError;
      }

      const executedAt = new Date().toISOString();

      // The executed master. Best-effort here for the same reason acceptance
      // never fails on a renderer outage — the vault's save-missing path and
      // the first download both regenerate from the frozen version row.
      let executedPath: string | null = null;
      let executedBytes: number | null = null;
      try {
        const { data: signatureRows } = await supabase.from(SIGNATURES_TABLE)
          .select('*').eq('version_id', version.id);
        const execution = executionContextFromSignatures(signatureRows ?? []);
        execution.executedAt = executedAt;
        const stored = await renderAndStoreVersionPdf(supabase, supabaseUrl, existing, version, 'executed', execution);
        executedPath = stored.path;
        executedBytes = stored.bytes;
      } catch (e) {
        console.error('[partner-agreements] executed PDF generation deferred:', e instanceof Error ? e.message : e);
      }

      await supabase.from(VERSIONS_TABLE).update({
        status: 'executed',
        executed_at: executedAt,
        executed_pdf_storage_path: executedPath,
        executed_pdf_bytes: executedBytes,
      }).eq('id', version.id);

      const { data: updated, error: updateError } = await supabase.from(TABLE).update({
        status: 'active',
        activated_at: executedAt,
        executed_at: executedAt,
        executed_pdf_storage_path: executedPath,
        signed_pdf_storage_path: executedPath,
        updated_by: staffId(actorId),
      }).eq('id', id).eq('status', 'partially_signed').select().single();
      if (updateError) throw updateError;

      await logEvent(supabase, id, 'counter_signed', actorId, actorLabel,
        `Counter-executed by ${signatory_name} — agreement fully executed`, {
          version_label: version.version_label,
          executed_pdf_storage_path: executedPath,
        });
      await logEvent(supabase, id, 'fully_executed', actorId, actorLabel,
        'Fully executed agreement archived', { version_label: version.version_label });

      await notifyPartner(supabase, existing.finance_agent_contact_id, {
        type: 'agreement_executed',
        title: 'Agreement fully executed',
        body: 'All parties have signed. The executed copy is available in your portal.',
        link: `/finance/agreements/${id}`,
        agreementId: id,
      });
      await insertTargetedNotification(supabase, {
        moduleKey: 'agreements',
        notification: {
          type: 'partner_agreement_activity',
          title: 'Agreement fully executed',
          message: `${existing.partner_legal_name} — version ${version.version_label} is fully executed and stored in Agreements.`,
          entity_id: id,
          link: `/partner-agreements/${id}`,
        },
      });

      return json({ agreement: updated, executed_pdf_storage_path: executedPath }, corsHeaders);
    }

    // ─── RESOLVE A CHANGE REQUEST ───────────────────────────
    if (action === 'resolve_change_request') {
      const { id, request_id, resolution, resolution_note } = body;
      if (!id || !request_id) return json({ error: 'id_required' }, corsHeaders, 400);
      if (resolution !== 'resolved' && resolution !== 'declined') {
        return json({ error: 'resolution_invalid' }, corsHeaders, 400);
      }

      const { data: request } = await supabase.from(CHANGE_REQUESTS_TABLE)
        .select('*').eq('id', request_id).eq('agreement_id', id).maybeSingle();
      if (!request) return json({ error: 'not_found' }, corsHeaders, 404);
      if (request.status !== 'open') return json({ error: 'already_resolved' }, corsHeaders, 409);

      const { data, error } = await supabase.from(CHANGE_REQUESTS_TABLE).update({
        status: resolution,
        resolved_by: staffId(actorId),
        resolved_by_label: actorLabel,
        resolved_at: new Date().toISOString(),
        resolution_note: resolution_note ?? null,
      }).eq('id', request_id).select().single();
      if (error) throw error;

      await logEvent(supabase, id, `change_request_${resolution}`, actorId, actorLabel,
        `Change request ${resolution}${resolution_note ? ` — ${resolution_note}` : ''}`,
        { request_id, section_key: request.section_key });

      return json({ change_request: data }, corsHeaders);
    }

    // ─── SET OWNER ──────────────────────────────────────────
    if (action === 'set_owner') {
      const { id, owner_id, owner_label } = body;
      if (!id) return json({ error: 'id_required' }, corsHeaders, 400);
      const { data, error } = await supabase.from(TABLE).update({
        agreement_owner_id: owner_id ?? null,
        agreement_owner_label: owner_label ?? null,
        updated_by: staffId(actorId),
      }).eq('id', id).select().single();
      if (error) throw error;
      await logEvent(supabase, id, 'owner_changed', actorId, actorLabel,
        `Agreement owner set to ${owner_label ?? 'unassigned'}`, { owner_id: owner_id ?? null });
      return json({ agreement: data }, corsHeaders);
    }

    // ─── NEW VERSION (vary an active agreement) ─────────────
    if (action === 'new_version') {
      const { id } = body;
      if (!id) return json({ error: 'id_required' }, corsHeaders, 400);

      const { data: existing, error: fetchErr } = await supabase
        .from(TABLE).select('*').eq('id', id).maybeSingle();
      if (fetchErr) throw fetchErr;
      if (!existing) return json({ error: 'not_found' }, corsHeaders, 404);

      const clone: Record<string, unknown> = { ...existing };
      for (const key of [
        'id', 'created_at', 'updated_at', 'activated_at', 'terminated_at', 'termination_reason',
        'docusign_envelope_id', 'docusign_status', 'docusign_sent_at', 'docusign_signed_at',
        'pdf_storage_path', 'signed_pdf_storage_path',
        'issued_at', 'issued_version_id', 'first_viewed_at', 'accepted_at',
        'executed_at', 'withdrawn_at', 'executed_pdf_storage_path',
      ]) delete clone[key];

      clone.status = 'draft';
      clone.version = (existing.version ?? 1) + 1;
      clone.supersedes_agreement_id = existing.id;
      clone.created_by = staffId(actorId);
      clone.updated_by = staffId(actorId);

      const { data, error } = await supabase.from(TABLE).insert(clone).select().single();
      if (error) throw error;

      await logEvent(supabase, data.id, 'version_created', actorId, actorLabel,
        `Version ${data.version} drafted from version ${existing.version}`, { supersedes: existing.id });
      await logEvent(supabase, existing.id, 'version_superseded_pending', actorId, actorLabel,
        `Version ${data.version} drafted`, { successor: data.id });

      return json({ agreement: data }, corsHeaders);
    }

    // ─── VOID (declare the agreement of no effect) ──────────
    if (action === 'void_agreement') {
      const { id } = body;
      const reason = typeof body.reason === 'string' ? body.reason.trim() : '';
      if (!id) return json({ error: 'id_required' }, corsHeaders, 400);
      // Voiding is permanent and appears in the compliance chain as critical.
      // An unexplained one is worse than useless to whoever reads it later.
      if (reason.length < MIN_VOID_REASON) {
        return json({
          error: 'reason_required',
          message: `Record why this agreement is being voided (at least ${MIN_VOID_REASON} characters). It is permanent and appears in the audit record.`,
        }, corsHeaders, 422);
      }

      const { data: existing } = await supabase.from(TABLE).select('*').eq('id', id).maybeSingle();
      if (!existing) return json({ error: 'not_found' }, corsHeaders, 404);
      if (existing.status === 'void') {
        return json({ error: 'already_void', message: 'This agreement is already void.' }, corsHeaders, 409);
      }
      if (!canVoid(existing.status)) {
        return json({
          error: 'transition_not_allowed',
          message: existing.status === 'active'
            ? 'A fully executed agreement cannot be voided — the parties were bound. Terminate it, or supersede it with a new version.'
            : `An agreement in "${existing.status}" cannot be voided.`,
        }, corsHeaders, 409);
      }

      const voidedAt = new Date().toISOString();
      const { data, error } = await supabase.from(TABLE).update({
        status: 'void',
        voided_at: voidedAt,
        void_reason: reason,
        updated_by: staffId(actorId),
      }).eq('id', id).eq('status', existing.status).select().single();
      if (error) throw error;

      // Anything still standing as live in front of the partner stops being
      // live. Executed version rows are never touched — an executed document
      // is history, and this row could not have reached void carrying one.
      await supabase.from(VERSIONS_TABLE)
        .update({ status: 'withdrawn' })
        .eq('agreement_id', id)
        .in('status', ['issued', 'superseded']);

      await logEvent(supabase, id, 'void', actorId, actorLabel,
        `Agreement voided — ${reason}`, { from: existing.status, reason });

      // Only tell a partner about a document they were actually sent.
      if (existing.issued_at) {
        await notifyPartner(supabase, existing.finance_agent_contact_id, {
          type: 'agreement_voided',
          title: 'Agreement voided',
          body: 'The issuing organisation has voided this agreement. It is of no effect and cannot be executed.',
          link: `/finance/agreements/${id}`,
          agreementId: id,
        });
      }

      return json({ agreement: data }, corsHeaders);
    }

    // ─── ARCHIVE / RESTORE (a filing decision, nothing more) ─
    if (action === 'archive' || action === 'restore') {
      const { id } = body;
      if (!id) return json({ error: 'id_required' }, corsHeaders, 400);

      const { data: existing } = await supabase.from(TABLE)
        .select('id, status, archived_at, partner_legal_name').eq('id', id).maybeSingle();
      if (!existing) return json({ error: 'not_found' }, corsHeaders, 404);

      if (action === 'archive') {
        if (existing.archived_at) {
          return json({ error: 'already_archived', message: 'This agreement is already archived.' }, corsHeaders, 409);
        }
        if (!canArchive(existing.status)) {
          return json({ error: 'not_archivable', message: archiveRefusal(existing.status) }, corsHeaders, 409);
        }
      } else if (!existing.archived_at) {
        return json({ error: 'not_archived', message: 'This agreement is not archived.' }, corsHeaders, 409);
      }

      const archiving = action === 'archive';
      const note = typeof body.reason === 'string' && body.reason.trim() ? body.reason.trim() : null;
      const { data, error } = await supabase.from(TABLE).update({
        archived_at: archiving ? new Date().toISOString() : null,
        archived_by: archiving ? staffId(actorId) : null,
        archived_by_label: archiving ? actorLabel : null,
        archive_reason: archiving ? note : null,
        updated_by: staffId(actorId),
      }).eq('id', id).select().single();
      if (error) throw error;

      await logEvent(supabase, id, archiving ? 'archived' : 'restored', actorId, actorLabel,
        archiving
          ? `Agreement archived${note ? ` — ${note}` : ''}`
          : 'Agreement restored to the working list',
        { status: existing.status, note });

      return json({ agreement: data }, corsHeaders);
    }

    // ─── DELETE (only what never left the building) ─────────
    // `delete_draft` is the original name and keeps working; both land here,
    // which also closes the hole in the old rule — it checked only that the
    // status said "draft", and a reverted agreement the partner had already
    // seen says exactly that.
    if (action === 'delete_agreement' || action === 'delete_draft') {
      const { id } = body;
      if (!id) return json({ error: 'id_required' }, corsHeaders, 400);

      const { data: existing } = await supabase.from(TABLE).select('*').eq('id', id).maybeSingle();
      if (!existing) return json({ error: 'not_found' }, corsHeaders, 404);

      // Counted here rather than inferred from the row: the row's own columns
      // can be cleared by a revision, the child tables cannot.
      const [versions, signatures, successors] = await Promise.all([
        supabase.from(VERSIONS_TABLE).select('id', { count: 'exact', head: true }).eq('agreement_id', id),
        supabase.from(SIGNATURES_TABLE).select('id', { count: 'exact', head: true }).eq('agreement_id', id),
        supabase.from(TABLE).select('id', { count: 'exact', head: true }).eq('supersedes_agreement_id', id),
      ]);

      const verdict = agreementDeleteVerdict({
        status: existing.status,
        issuedVersionCount: versions.count ?? 0,
        signatureCount: signatures.count ?? 0,
        issuedAt: existing.issued_at ?? null,
        executedPdfPath: existing.executed_pdf_storage_path ?? null,
        supersededByCount: successors.count ?? 0,
      });
      if (!verdict.ok) {
        return json({ error: verdict.code, message: verdict.reason }, corsHeaders, 409);
      }

      // Written BEFORE the delete and straight into the compliance chain
      // rather than through `logEvent`: `partner_agreement_events` cascades
      // away with the row, while `partner_compliance_audit_events` keeps the
      // agreement id as its `chain_key` after the foreign key goes null. The
      // deletion of a record is itself a record.
      await recordPartnerAudit(supabase, {
        agreement_id: id,
        scope_type: 'agreement',
        scope_id: id,
        actor_id: staffId(actorId),
        actor_label: actorLabel,
        severity: 'critical',
        category: 'lifecycle',
        action: 'agreement_deleted',
        target_type: 'partner_agreement',
        target_id: id,
        description: `Agreement permanently deleted (${existing.status}) — ${existing.partner_legal_name}`,
        metadata: {
          status: existing.status,
          direction: existing.direction,
          partner_legal_name: existing.partner_legal_name,
          version: existing.version,
          created_at: existing.created_at,
          reason: typeof body.reason === 'string' ? body.reason.trim() || null : null,
        },
      });

      const { error } = await supabase.from(TABLE).delete().eq('id', id);
      if (error) throw error;
      return json({ success: true }, corsHeaders);
    }

    // ─── RESOLVE EFFECTIVE SCHEDULE (used by commission engine) ──
    // Also deliberately blind to `archived_at`, and this one matters most:
    // archiving is one person tidying one list, and it must never be able to
    // change what a partner gets paid.
    if (action === 'effective_schedule') {
      const { finance_agent_contact_id, direction } = body;
      if (!finance_agent_contact_id) return json({ error: 'finance_agent_contact_id_required' }, corsHeaders, 400);

      const { data, error } = await supabase
        .from(TABLE)
        .select('*')
        .eq('finance_agent_contact_id', finance_agent_contact_id)
        .eq('direction', direction && DIRECTIONS.has(direction) ? direction : 'outbound_finance_referral')
        .eq('status', 'active')
        .order('version', { ascending: false })
        .limit(1);
      if (error) throw error;

      return json({ agreement: data?.[0] ?? null }, corsHeaders);
    }

    return json({ error: 'unknown_action' }, corsHeaders, 400);
  } catch (err) {
    // PostgREST rejects with a plain `{message, code, details, hint}` object, not
    // an Error — `err instanceof Error` was false for every database failure, so
    // the real cause was replaced by the useless string "Unexpected error".
    const asRecord = (err ?? {}) as Record<string, unknown>;
    const message = err instanceof Error
      ? err.message
      : (typeof asRecord.message === 'string' && asRecord.message)
        || (typeof err === 'string' ? err : JSON.stringify(err));
    console.error('[manage-partner-agreements] error:', message, {
      code: asRecord.code ?? null,
      details: asRecord.details ?? null,
      hint: asRecord.hint ?? null,
      stack: err instanceof Error ? err.stack : null,
    });
    return json({
      error: message || 'Unexpected error',
      code: asRecord.code ?? null,
      details: asRecord.details ?? null,
      hint: asRecord.hint ?? null,
    }, corsHeaders, 500);
  }
});
