export type MarketSourceType = 'rss' | 'atom' | 'official_api' | 'html_listing' | 'licensed_partner_feed' | 'manual' | 'feed_with_html_fallback' | 'rss_with_html_fallback' | 'rss_multi' | 'html_listing_or_licensed_feed';
export type MarketUpdateCategory = 'finance' | 'property_market' | 'construction' | 'policy_regulation' | 'rental_market' | 'economy' | 'planning_supply' | 'political' | 'other';
export type MarketGeography = 'Australia' | 'NSW' | 'VIC' | 'QLD' | 'WA' | 'SA' | 'TAS' | 'ACT' | 'NT' | 'Multi';
export type MarketImpactLevel = 'low' | 'medium' | 'high' | 'critical';
export type MarketAudienceTag = 'investors' | 'owner_occupiers' | 'first_home_buyers' | 'smsf' | 'developers' | 'buyers_agents' | 'mortgage_brokers' | 'property_managers' | 'builders' | 'finance_brokers';
export type MarketUpdateStatus = 'candidate' | 'published' | 'ignored' | 'failed';
export type MarketSourceReliabilityTier = 'official' | 'tier_1_media' | 'industry' | 'partner' | 'manual' | 'watchlist';
export type MarketSegment = 'finance' | 'property' | 'construction' | 'political' | 'economic' | 'social' | 'policy_regulation' | 'rental';
export type MarketFreshnessTier = 'breaking' | 'today' | 'this_week' | 'older';
export type MarketDigestPeriod = '24h' | 'weekly' | 'biweekly' | 'monthly' | 'quarterly' | 'annual';

export interface MarketSourceSeed { source_key:string; display_name:string; description:string; adapter_type:MarketSourceType; primary_url:string; feed_urls:string[]; listing_urls:string[]; source_authority:string; reliability_tier:MarketSourceReliabilityTier; default_segments:MarketSegment[]; default_category:MarketUpdateCategory; default_geography:MarketGeography[]; refresh_frequency_minutes:number; enabled:boolean; copyright_mode:string; extraction_policy:Record<string,unknown>; source_weight:number; relevant_keywords:string[]; excluded_keywords:string[]; perspective:string|null; adapter_config:Record<string,string>; }
export interface MarketSource { id: string; source_key?:string|null; name: string; description?: string | null; source_type: MarketSourceType; adapter_type?:MarketSourceType|null; url: string; primary_url?:string|null; feed_urls?:string[]; listing_urls?:string[]; adapter_config?:Record<string,unknown>; source_authority?:string|null; perspective?:string|null; copyright_mode?:string|null; category: MarketUpdateCategory; geography: MarketGeography; reliability_tier: MarketSourceReliabilityTier; enabled: boolean; refresh_frequency_hours: number; refresh_frequency_minutes?:number; consecutive_failures?:number; health_status?:'healthy'|'degraded'|'failed'|'disabled'; last_http_status?:number|null; last_latency_ms?:number|null; last_items_discovered?:number; last_items_published?:number; last_fetched_at?: string | null; last_success_at?: string | null; last_error?: string | null; created_at: string; updated_at: string; }
export interface MarketUpdate { id: string; source_id?: string | null; source_name: string; source_url: string; canonical_url?:string|null; original_url?:string|null; source_authority?:string|null; source_perspective?:string|null; author?:string|null; public_excerpt?:string|null; source_published_at?: string | null; ingested_at: string; title: string; slug?: string | null; category: MarketUpdateCategory; segments: MarketSegment[]; freshness_tier: MarketFreshnessTier; geography: MarketGeography[]; impact_level: MarketImpactLevel; audience_tags: MarketAudienceTag[]; raw_excerpt?: string | null; raw_content_hash?: string | null; ai_summary?: string | null; key_points: string[]; why_it_matters?: string | null; property_implications?: string | null; finance_implications?: string | null; policy_implications?: string | null; risk_flags: string[]; lending_criteria_tags?:string[]; legal_topics?:string[]; economic_topics?:string[]; legal_status?:string|null; effective_date?:string|null; confidence_score?: number | null; citation_urls: string[]; relevance_score: number; status: MarketUpdateStatus; failure_reason?: string | null; dedupe_hash: string; created_at: string; updated_at: string; }
export interface MarketDigest24h { id: string; period: MarketDigestPeriod; generated_at: string; period_start: string; period_end: string; executive_summary: string; top_update_ids: string[]; finance_lending_highlights: string[]; property_market_highlights: string[]; construction_supply_highlights: string[]; policy_regulation_highlights: string[]; political_economic_watchpoints: string[]; social_watchpoints: string[]; segment_breakdown: Record<string, { headline?: string; highlights?: string[]; implications?: string }>; buyer_implications?: string | null; investor_implications?: string | null; broker_adviser_implications?: string | null; client_advisory_implications: string[]; recommended_watchlist_for_tomorrow: string[]; source_urls: string[]; confidence_score?: number | null; status: 'published' | 'draft' | 'failed' | 'no_data'; }
export interface MarketQAKeyFigure { label: string; value: string; source_id?: string }
export type MarketQATimeHorizon = 'immediate' | 'short_term' | 'medium_term' | 'long_term' | 'unclear';
export type MarketQASentiment = 'positive' | 'neutral' | 'cautious' | 'negative';
export interface MarketQARetrievedItem { id: string; title: string; source_name: string; source_url: string; source_published_at?: string | null; impact_level?: string | null; used: boolean; }
export interface MarketQAMessage { id: string; role: 'user' | 'assistant'; content: string; citations: string[]; source_update_ids: string[]; confidence_score?: number | null; limitations: string[]; created_at: string; follow_up_questions?: string[]; key_figures?: MarketQAKeyFigure[]; time_horizon?: MarketQATimeHorizon; sentiment?: MarketQASentiment; model_used?: string; retrieved?: MarketQARetrievedItem[]; question_id?: string | null; rate_limited?: boolean; }
export interface MarketUpdateFilters { category?: MarketUpdateCategory | 'all'; geography?: MarketGeography | 'all'; impact?: MarketImpactLevel | 'all'; audience?: MarketAudienceTag | 'all'; segment?: MarketSegment | 'all'; freshness?: MarketFreshnessTier | 'all'; search?: string; dateRange?: { from?: string; to?: string }; status?: MarketUpdateStatus; limit?: number; }
export interface MarketIngestionSummary { runId?:string; status?:MarketIngestionRun['status']; active?:boolean; sourcesConsidered?:number; sourcesProcessed?:number; sourcesSucceeded?:number; sourcesFailed?:number; ingested: number; published: number; candidates: number; ignored: number; failed: number; skippedDuplicates: number; sourceErrors: Array<{ sourceId: string; message: string }>; message?: string; }
export interface NormalisedMarketSourceItem { source_id?: string | null; source_name: string; source_url: string; source_published_at?: string | null; title: string; excerpt?: string | null; content?: string | null; category?: MarketUpdateCategory; geography?: MarketGeography[]; audience_tags?: MarketAudienceTag[]; }
export interface MarketIngestionRun { id:string; trigger_type:'cron'|'page_open'|'manual'|'digest_prerequisite'|'retry'|'source_test'; started_at:string; completed_at?:string|null; status:'queued'|'running'|'completed'|'partial'|'failed'|'skipped_fresh'; sources_considered:number; sources_processed:number; sources_succeeded:number; sources_failed:number; items_discovered:number; items_published:number; duration_ms?:number|null; error_summary?:string|null; }
export interface MarketSourceHealth { totalSources: number; enabledSources: number; healthySources:number; degradedSources:number; failedSources: number; lastFetchedAt?: string | null; lastSuccessAt?: string | null; lastError?: string | null; latestRun?:MarketIngestionRun|null; }
export interface MarketQASourceContext { update_id: string; title: string; summary: string; citations: string[]; source_url: string; }
export interface MarketDigestGenerationResult { digest: MarketDigest24h | null; message: string; noData: boolean; }
