// GENERATED — do not edit. Run `npm run mobile:dart:api`.
//
// Source: mobile/api-surface.json (generated from the audited security
// registry). `mobileScope` decides which app may call which function —
// see mobile/plan.md R-ARCH-4 and scripts/mobile/check-api-scope.mjs.
//
// Counts: staff 242 · portal 70 · public 40 · server-only 71
//
// This file's shape is owned by its generator; formatting it would make it
// disagree with the drift check, so the formatter is told to leave it alone.
// dart format off

/// Which family of apps a function belongs to.
enum NpcFunctionScope {
  /// Command Centre only.
  staff,

  /// The four portal apps only.
  portal,

  /// Any app — unauthenticated or pre-auth surfaces.
  public,

  /// No client, ever. Present so a refusal can explain itself.
  serverOnly,
}

/// The edge-function catalogue, classified by scope.
///
/// This is a contract, not a convenience: calling a function outside the
/// running app's scope is a build failure, because the alternative is a
/// client that reaches an endpoint its session can never satisfy and fails
/// at runtime in front of a user.
class NpcFunctions {
  const NpcFunctions._();

  /// Command Centre surface.
  static const Set<String> staff = <String>{
    'abs-data-service',
    'abs-seifa-service',
    'admin-user-management',
    'agent-insights-runner',
    'agent-skill-marketplace',
    'agreement-centre-render',
    'ai-dashboard-agent',
    'airtable-proxy',
    'aml-access',
    'aml-ai-guardrail',
    'aml-cases',
    'aml-client-portal',
    'aml-entities',
    'aml-finance',
    'aml-launch-ops',
    'aml-monitoring',
    'aml-records',
    'aml-release-gate',
    'aml-reporting',
    'aml-resilience',
    'aml-risk',
    'aml-step-up',
    'aml-tenant',
    'aml-transactions',
    'aml-verification',
    'analytics-query',
    'analyze-meta-ads',
    'analyze-meta-ads-phase2',
    'analyze-meta-ads-phase3',
    'analyze-meta-ads-phase4',
    'analyze-meta-ads-phase5',
    'archive-old-reports',
    'authenticated-data',
    'builder-collaboration-admin',
    'builder-construction-admin',
    'builder-delivery-admin',
    'builder-inventory-admin',
    'builder-portal-admin',
    'builder-portal-invite',
    'builder-projects-admin',
    'builder-transactions-admin',
    'builder-workspace-admin',
    'calculate-borrowing-capacity',
    'cdr-lending-rates-service',
    'check-integration-secrets',
    'check-model-availability',
    'clean-note-transcript',
    'client-portal-invite',
    'cloudflare-proxy',
    'commercial-bc-scenario-agent',
    'compare-cash-flow-reports',
    'compare-investment-reports',
    'condense-investment-report',
    'convert-template-document',
    'cotality-service',
    'create-advanced-client',
    'data-conflict-resolver',
    'diagnose-ghl-attribution',
    'domain-data-service',
    'email-copilot',
    'email-copilot-extras',
    'enrich-lead-attributions',
    'estimate-commercial-caprate',
    'estimate-commercial-noi',
    'estimate-property-expenses',
    'execute-workflow-step',
    'feature-flags-admin',
    'fetch-meta-ads',
    'figma-template-sync',
    'finance-portal-admin',
    'finance-portal-automations',
    'finance-portal-briefing-runner',
    'finance-portal-commissions',
    'finance-portal-invite',
    'finance-portal-tri-portal-health',
    'financial-calculator-service',
    'financial-validation-service',
    'fix-report-status',
    'fork-investment-report',
    'format-comparison-report',
    'generate-brand-design-system',
    'generate-bulk-reports',
    'generate-chart-analysis',
    'generate-chart-images',
    'generate-charts-python',
    'generate-commission-payout',
    'generate-investment-report',
    'generate-market-intelligence-report',
    'generate-portfolio-analysis',
    'get-activity-logs',
    'get-api-usage-stats',
    'get-call-logs',
    'get-call-recording',
    'get-client-data',
    'get-email-data',
    'get-investment-reports',
    'get-system-logs',
    'get-token-event-trail',
    'get-user-names',
    'ghl-account-preview',
    'ghl-calendar',
    'ghl-calendar-proxy',
    'ghl-calendar-test',
    'ghl-marketing-dump-export',
    'ghl-marketing-raw-dump',
    'ghl-test-credentials',
    'ghl-workflow-visualizer',
    'google-fonts-catalog',
    'hero-image-studio',
    'import-clients-from-ghl',
    'import-from-url',
    'import-schools-data',
    'import-suburb-directory',
    'internal-message-attachments',
    'internal-messaging',
    'investment-scoring-service',
    'legal-matters-admin',
    'list-token-audit',
    'list-token-usage',
    'listing-enrichment',
    'listing-images',
    'listings-cache',
    'location-intelligence-service',
    'log-activity',
    'manage-agency-agreements',
    'manage-automation-settings',
    'manage-bc-scenarios',
    'manage-branding',
    'manage-call-logs',
    'manage-call-settings',
    'manage-ci-assessments',
    'manage-client-data',
    'manage-commercial-data',
    'manage-commission-ledger',
    'manage-compliance-records',
    'manage-data-import',
    'manage-generated-documents',
    'manage-industrial-data',
    'manage-investment-reports',
    'manage-lead-magnets',
    'manage-lender-favourites',
    'manage-lender-rate-alerts',
    'manage-lender-submissions',
    'manage-partner-agreements',
    'manage-report-preferences',
    'manage-template-library',
    'manage-templates',
    'manychat-proxy',
    'market-news-archive-v2',
    'market-updates-archive',
    'market-updates-curate',
    'market-updates-feed',
    'market-updates-qa',
    'market-updates-status',
    'market-updates-voice-transcribe',
    'mcp',
    'message-governance',
    'migrate-comparison-scores',
    'migration-job-status',
    'migration-upload-source',
    'mission-control-balance',
    'mission-control-catalog',
    'mission-control-devices',
    'mission-control-feedback-prompt',
    'mission-control-handoff',
    'mission-control-invoices',
    'mission-control-key-info',
    'mission-control-packs',
    'mission-control-payment-methods',
    'mission-control-plan-change',
    'mission-control-purchases',
    'mission-control-rotate-key',
    'mission-control-seats',
    'notifications-feed',
    'notifications-feed-v2',
    'one-time-bulk-conversation-sync',
    'outlook-calendar',
    'outlook-email-sync',
    'outlook-manage-subscription',
    'parse-formara-pdf',
    'parse-property-pdf',
    'parse-template-document',
    'partner-agreement-records',
    'partner-compliance',
    'pdf-import-client-report',
    'pdf-import-diagnostics',
    'pdf-import-monitoring',
    'pdf-import-retention',
    'pdf-parse-recover-stuck-jobs',
    'prepare-report-hero-images',
    'push-unsubscribe',
    'quantitative-report-pipeline',
    'rba-data-service',
    'reclassify-property',
    'regenerate-report-qualitative',
    'render-borrowing-capacity-pdf',
    'render-cash-flow-comparison-pdf',
    'render-cash-flow-pdf',
    'render-client-details-pdf',
    'render-commercial-capacity-pdf',
    'render-investment-report-pdf',
    'render-market-intelligence-pdf',
    'render-portfolio-review-pdf',
    'render-property-comparison-pdf',
    'render-report-qa-pdf',
    'render-source',
    'render-template-pdf',
    'report-engine-agent',
    'report-engine-inspector',
    'report-qa',
    'report-schema-validator',
    'resolve-listing-coordinates',
    'retrieve-template-context',
    'risk-assessment-service',
    'scrape-property-listing',
    'secure-storage',
    'security-step-up',
    'send-appointment-notification',
    'send-call-alert-email',
    'send-email-reply',
    'send-ghl-message',
    'send-weekly-call-report',
    'share-report-with-finance',
    'solicitor-portal-admin',
    'solicitor-portal-invite',
    'sqm-rent-service',
    'staff-client-portal-handoff-create',
    'street-view',
    'sync-client-to-ghl',
    'sync-ghl-conversations',
    'sync-ghl-marketing-assets',
    'sync-ghl-pipelines',
    'sync-notes-to-ghl',
    'template-ai-author',
    'template-analytics',
    'template-design-agent',
    'template-import-pdf',
    'update-ghl-opportunity-stage',
    'update-integration-secret',
    'update-stamp-duty-rates',
    'user-guide-assistant',
    'voice-to-text',
  };

  /// Client / finance / solicitor / builder surface.
  static const Set<String> portal = <String>{
    'agent-models-read',
    'bc-scenario-agent',
    'builder-portal-change-password',
    'builder-portal-collaboration',
    'builder-portal-construction',
    'builder-portal-delivery',
    'builder-portal-inventory',
    'builder-portal-logout',
    'builder-portal-projects',
    'builder-portal-transactions',
    'builder-portal-verify',
    'builder-portal-workspace',
    'client-legal-workspace',
    'client-portal-batch6',
    'client-portal-comms',
    'client-portal-finance-hub',
    'finance-legal-coordination',
    'finance-portal-agreements',
    'finance-portal-ai-copilot',
    'finance-portal-aml-requests',
    'finance-portal-audit-timeline',
    'finance-portal-batch6',
    'finance-portal-batch7',
    'finance-portal-batch8',
    'finance-portal-batch9-10',
    'finance-portal-broker-kpis',
    'finance-portal-bulk-actions',
    'finance-portal-change-password',
    'finance-portal-client-comms',
    'finance-portal-client-data',
    'finance-portal-client-mirror',
    'finance-portal-client-tasks',
    'finance-portal-dashboard-metrics',
    'finance-portal-deal-trackers',
    'finance-portal-document-requirements',
    'finance-portal-documents',
    'finance-portal-engagement',
    'finance-portal-forecasting',
    'finance-portal-handoff-create',
    'finance-portal-lender-intelligence',
    'finance-portal-lender-packet',
    'finance-portal-messages',
    'finance-portal-notifications',
    'finance-portal-nudges',
    'finance-portal-pipeline',
    'finance-portal-purchase-files',
    'finance-portal-saved-views',
    'finance-portal-settings',
    'finance-portal-settlement-runway',
    'finance-portal-snoozes',
    'finance-portal-templates',
    'get-portal-client-data',
    'manage-agent-models',
    'manage-loan-writer-undertakings',
    'manage-partner-referrals',
    'manage-portal-client-data',
    'market-qa-share',
    'phase6-quality-ops',
    'portal-book-appointment',
    'portal-upload-file',
    'push-subscribe',
    'solicitor-portal-change-password',
    'solicitor-portal-comms',
    'solicitor-portal-compliance',
    'solicitor-portal-documents',
    'solicitor-portal-intelligence',
    'solicitor-portal-logout',
    'solicitor-portal-matters',
    'solicitor-portal-verify',
    'staff-client-portal-messages',
  };

  /// Callable from any app.
  static const Set<String> public = <String>{
    'abs-employment-service',
    'admin-password-reset',
    'aml-reliance',
    'builder-portal-accept-invite',
    'builder-portal-forgot-password',
    'builder-portal-login',
    'builder-portal-reset-password',
    'client-portal-accept-invite',
    'client-portal-forgot-password',
    'client-portal-login',
    'client-portal-logout',
    'client-portal-reset-password',
    'client-portal-verify',
    'climate-data-service',
    'crime-statistics-service',
    'custom-auth-login',
    'custom-auth-login-v2',
    'custom-auth-logout',
    'custom-auth-logout-v2',
    'custom-auth-verify',
    'custom-auth-verify-v2',
    'finance-email-track-pixel',
    'finance-portal-accept-invite',
    'finance-portal-forgot-password',
    'finance-portal-handoff-redeem',
    'finance-portal-login',
    'finance-portal-logout',
    'finance-portal-reset-password',
    'finance-portal-verify',
    'get-vapid-public-key',
    'google-places-autocomplete',
    'partner-consent-portal',
    'public-transport-service',
    'request-lead-magnet',
    'school-data-service',
    'solicitor-portal-accept-invite',
    'solicitor-portal-forgot-password',
    'solicitor-portal-login',
    'solicitor-portal-reset-password',
    'template-share',
  };

  /// Never callable from a device.
  static const Set<String> serverOnly = <String>{
    'agent-planner',
    'agent-task-runner',
    'aml-idv-retention',
    'aml-provider-webhook',
    'aml-verification-processor',
    'auto-report-sync',
    'auto-report-webhook',
    'backfill-investment-scores',
    'backfill-lead-attributions',
    'backfill-message-directions',
    'backfill-notes-to-ghl',
    'backfill-opportunity-mappings',
    'bootstrap-cron-vault',
    'build-conversations-export-worker',
    'builder-document-processor',
    'cleanup-call-log-names',
    'cleanup-stale-calls',
    'conversation-sync-cron',
    'cross-portal-outbox-worker',
    'didit-webhook',
    'dispatch-marketing-reports',
    'dispatch-workflow-triggers',
    'email-body-backfill',
    'email-sync-cron',
    'ghl-conversations-cron',
    'ghl-legacy-backfill-gaps',
    'ghl-legacy-wipe-orchestrator',
    'ghl-legacy-wipe-worker',
    'ghl-marketing-dump-enqueue',
    'ghl-marketing-dump-worker',
    'ghl-migrate-bookings-worker',
    'ghl-migrate-calendar-groups-worker',
    'ghl-migrate-calendars-worker',
    'ghl-migrate-contacts-worker',
    'ghl-migrate-conversations-replay-worker',
    'ghl-migrate-conversations-reset-phantoms',
    'ghl-migrate-conversations-worker',
    'ghl-migrate-notes-worker',
    'ghl-migrate-opportunities-worker',
    'ghl-migrate-workflow-enrollments-worker',
    'ghl-migrate-workflow-reenroll-worker',
    'ghl-migrate-workflows-snapshot-worker',
    'ghl-webhook-receiver',
    'healthcheck-ping',
    'legal-document-processor',
    'market-qa-digest-runner',
    'market-qa-quality-report',
    'market-qa-quality-snapshot',
    'market-qa-subscriptions',
    'market-source-relay',
    'market-updates-digest',
    'market-updates-embed-backfill',
    'market-updates-ingest',
    'market-updates-source-admin',
    'migration-dispatcher',
    'migration-job-control',
    'migration-orchestrator',
    'mission-control-webhook',
    'outlook-email-webhook',
    'pdf-import-ssim-score',
    'pdf-parse-callback',
    'pdf-parse-chunk-callback',
    'pdf-parse-dispatch',
    'process-scheduled-emails',
    'report-api-usage',
    'resume-bulk-generation',
    'resume-investment-reports',
    'send-web-push',
    'start-conversations-export',
    'template-import-finalize-worker',
    'vapi-call-webhook',
  };

  /// Everything a [scope] app is permitted to call, including [public].
  static Set<String> allowedFor(NpcFunctionScope scope) {
    switch (scope) {
      case NpcFunctionScope.staff:
        return <String>{...staff, ...public};
      case NpcFunctionScope.portal:
        return <String>{...portal, ...public};
      case NpcFunctionScope.public:
        return public;
      case NpcFunctionScope.serverOnly:
        return const <String>{};
    }
  }

  /// The scope a function belongs to, or null if the registry does not know it.
  static NpcFunctionScope? scopeOf(String name) {
    if (staff.contains(name)) return NpcFunctionScope.staff;
    if (portal.contains(name)) return NpcFunctionScope.portal;
    if (public.contains(name)) return NpcFunctionScope.public;
    if (serverOnly.contains(name)) return NpcFunctionScope.serverOnly;
    return null;
  }
}
