import type * as XLSXTypes from 'xlsx';
import { createAdvancedDefaults } from '@/components/clients/add-client/defaults';
import { calculateFactFindTotals } from './calculations';
import { APPLICANT_FIELDS, ASSET_COLUMNS, EMPLOYMENT_FIELDS, LIABILITY_COLUMNS, LIVING_EXPENSE_ITEMS } from './fieldDefinitions';
import type { AdvancedClientCreationPayload } from './types';

export const MAX_EXCEL_FILE_BYTES=10*1024*1024;
export const EXCEL_ACCEPT={'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':['.xlsx'],'application/vnd.ms-excel':['.xls']};
export const RECOGNISED_SHEETS=['White Label Setup','Client Fact Find','Living Expenses','Client Form Output'] as const;
const REQUIRED_SHEETS=['Client Fact Find','Living Expenses'] as const;
export interface ExcelImportSummary { applicantsFound:number; addressesFound:number; employmentRecordsFound:number; assetsPopulated:number; liabilitiesPopulated:number; livingExpensesPopulated:number; warnings:number }
export interface ParsedExcelImport { payload:AdvancedClientCreationPayload; summary:ExcelImportSummary; warnings:string[]; fatalErrors:string[] }

export function validateExcelFile(file:Pick<File,'name'|'size'>):string|null {if(!/\.(xlsx|xls)$/i.test(file.name))return 'Unsupported file type. Select an .xlsx or .xls workbook.';if(file.size>MAX_EXCEL_FILE_BYTES)return 'The workbook is larger than the 10 MB maximum.';return null}
export async function parseAdvancedClientWorkbookFile(file:File):Promise<ParsedExcelImport>{const validationError=validateExcelFile(file);if(validationError)throw new Error(validationError);return parseAdvancedClientWorkbook(await file.arrayBuffer())}
const emptySummary=():ExcelImportSummary=>({applicantsFound:0,addressesFound:0,employmentRecordsFound:0,assetsPopulated:0,liabilitiesPopulated:0,livingExpensesPopulated:0,warnings:0});
const cell=(sheet:XLSXTypes.WorkSheet,address:string)=>sheet[address];
const text=(sheet:XLSXTypes.WorkSheet,address:string)=>{const current=cell(sheet,address);if(!current||current.v==null)return '';if(current.w&&current.t==='n'&&/phone|mobile/i.test(String(current.z??'')))return current.w.trim();return String(current.v).trim()};
const phoneText=(sheet:XLSXTypes.WorkSheet,address:string)=>{const current=cell(sheet,address);if(!current||current.v==null)return '';return String(current.t==='n'&&current.w?current.w:current.v).trim()};
const number=(sheet:XLSXTypes.WorkSheet,address:string)=>{const raw=cell(sheet,address)?.v;if(raw==null||raw==='')return 0;const parsed=typeof raw==='number'?raw:Number(String(raw).replace(/[$,%\s,]/g,''));return Number.isFinite(parsed)?parsed:0};
const percentage=(sheet:XLSXTypes.WorkSheet,address:string)=>{const current=cell(sheet,address),raw=number(sheet,address);return current&&typeof current.v==='number'&&/%/.test(String(current.z??current.w??''))&&Math.abs(raw)<=1?raw*100:raw};
const pad=(value:number)=>String(value).padStart(2,'0');
const date=(XLSX:typeof XLSXTypes,sheet:XLSXTypes.WorkSheet,address:string,warnings:string[],label:string):string|null=>{const raw=cell(sheet,address)?.v;if(raw==null||raw==='')return null;if(raw instanceof Date){if(Number.isNaN(raw.valueOf())){warnings.push(`${label} contains an invalid date.`);return null}return `${raw.getFullYear()}-${pad(raw.getMonth()+1)}-${pad(raw.getDate())}`}if(typeof raw==='number'){const parsed=XLSX.SSF.parse_date_code(raw);if(parsed)return `${parsed.y}-${pad(parsed.m)}-${pad(parsed.d)}`;warnings.push(`${label} contains an invalid Excel date.`);return null}const value=String(raw).trim(),iso=value.match(/^(\d{4})-(\d{1,2})-(\d{1,2})$/),au=value.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})$/);const parts=iso?[Number(iso[1]),Number(iso[2]),Number(iso[3])]:au?[Number(au[3]),Number(au[2]),Number(au[1])]:null;if(parts){const [year,month,day]=parts,valid=new Date(year,month-1,day);if(valid.getFullYear()===year&&valid.getMonth()===month-1&&valid.getDate()===day)return `${year}-${pad(month)}-${pad(day)}`}warnings.push(`${label} contains an invalid date.`);return null};
const hasContent=(record:object)=>Object.entries(record).some(([key,value])=>!['displayOrder','applicantNumber','relationship','expenseKey','category','itemLabel'].includes(key)&&value!==''&&value!==null&&value!==0);

export async function parseAdvancedClientWorkbook(data:ArrayBuffer):Promise<ParsedExcelImport>{
  const XLSX=await import('xlsx'),payload=createAdvancedDefaults(),warnings:string[]=[];
  let workbook:XLSXTypes.WorkBook;try{workbook=XLSX.read(data,{type:'array',cellDates:true})}catch{return {payload,summary:emptySummary(),warnings,fatalErrors:['The selected file is not a valid Excel workbook.']}}
  const missing=REQUIRED_SHEETS.filter(name=>!workbook.Sheets[name]);
  if(missing.length)return {payload,summary:emptySummary(),warnings,fatalErrors:[`Required worksheet${missing.length>1?'s are':' is'} missing: ${missing.join(', ')}.`]};
  const unexpected=workbook.SheetNames.filter(name=>!RECOGNISED_SHEETS.includes(name as typeof RECOGNISED_SHEETS[number]));if(unexpected.length)warnings.push(`Unrecognised worksheet${unexpected.length>1?'s were':' was'} ignored: ${unexpected.join(', ')}.`);
  const fact=workbook.Sheets['Client Fact Find'];
  ([0,1] as const).forEach(index=>{const column=index===0?'C':'G',applicant=payload.applicants[index]!;APPLICANT_FIELDS.forEach(field=>{const row=XLSX.utils.decode_cell(field.cell).r+1,address=`${column}${row}`,raw=field.type==='date'?date(XLSX,fact,address,warnings,`Applicant ${index+1} ${field.label}`):field.type==='integer'?number(fact,address):field.type==='phone'?phoneText(fact,address):text(fact,address);(applicant as unknown as Record<string,unknown>)[field.key]=raw});const rows=[['current',19,20,21,0],['previous',22,23,24,1]] as const;rows.forEach(([addressType,addressRow,livingRow,movedRow,displayOrder])=>{const target=payload.addresses.find(item=>item.applicantNumber===index+1&&item.addressType===addressType)!;target.address=text(fact,`${column}${addressRow}`);target.livingSituation=text(fact,`${column}${livingRow}`);target.movedInDate=date(XLSX,fact,`${column}${movedRow}`,warnings,`Applicant ${index+1} ${addressType} moved-in date`);target.displayOrder=displayOrder});const employment=payload.employment[index]!;EMPLOYMENT_FIELDS.forEach(field=>{const row=XLSX.utils.decode_cell(field.cell).r+1,address=`${column}${row}`;(employment as unknown as Record<string,unknown>)[field.key]=field.type==='date'?date(XLSX,fact,address,warnings,`Applicant ${index+1} ${field.label}`):field.type==='money'?number(fact,address):text(fact,address)})});
  payload.assets.forEach((asset,index)=>ASSET_COLUMNS.forEach((field,column)=>{const address=XLSX.utils.encode_cell({r:39+index,c:column});(asset as unknown as Record<string,unknown>)[field.key]=field.type==='money'?number(fact,address):field.type==='percentage'?percentage(fact,address):field.type==='date'?date(XLSX,fact,address,warnings,`Asset ${index+1} ${field.label}`):text(fact,address)}));
  payload.liabilities.forEach((liability,index)=>LIABILITY_COLUMNS.forEach((field,column)=>{const address=XLSX.utils.encode_cell({r:52+index,c:column});(liability as unknown as Record<string,unknown>)[field.key]=field.type==='money'?number(fact,address):field.type==='percentage'?percentage(fact,address):text(fact,address)}));
  const expenses=workbook.Sheets['Living Expenses'];payload.expenses=LIVING_EXPENSE_ITEMS.map(item=>{const row=item.displayOrder+5,workbookCategory=text(expenses,`A${row}`),workbookLabel=text(expenses,`B${row}`),matches=workbookCategory===item.category&&workbookLabel===item.itemLabel;if(!matches)warnings.push(`Living Expenses row ${row} did not match ${item.category} / ${item.itemLabel}; its value was not imported.`);return {expenseKey:item.key,category:item.category,itemLabel:item.itemLabel,displayOrder:item.displayOrder,monthlyAmount:matches?number(expenses,item.amountCell):0,notes:matches?text(expenses,item.notesCell):''}});
  payload.calculatedTotals=calculateFactFindTotals(payload);
  const summary={applicantsFound:payload.applicants.filter(hasContent).length,addressesFound:payload.addresses.filter(item=>Boolean(item.address||item.livingSituation||item.movedInDate)).length,employmentRecordsFound:payload.employment.filter(hasContent).length,assetsPopulated:payload.assets.filter(hasContent).length,liabilitiesPopulated:payload.liabilities.filter(hasContent).length,livingExpensesPopulated:payload.expenses.filter(item=>Number(item.monthlyAmount)>0||Boolean(item.notes.trim())).length,warnings:0};if(!summary.applicantsFound)warnings.push('No applicant details were found.');summary.warnings=warnings.length;return {payload,summary,warnings,fatalErrors:[]};
}
