import * as XLSX from 'xlsx';
import { readFileSync } from 'node:fs';
import { describe,expect,it } from 'vitest';
import { calculateFactFindTotals } from './calculations';
import { MAX_EXCEL_FILE_BYTES,parseAdvancedClientWorkbook,validateExcelFile } from './excelImport';

function workbook(sheets=['Client Fact Find','Living Expenses']){const book=XLSX.utils.book_new();for(const name of sheets){const sheet=XLSX.utils.aoa_to_sheet([]);if(name==='Client Fact Find'){Object.assign(sheet,{C7:{t:'s',v:' Alex '},C9:{t:'s',v:'Smith'},G7:{t:'s',v:'Taylor'},C10:{t:'n',v:45292,z:'dd/mm/yyyy'},C19:{t:'s',v:'1 Main Street'},C21:{t:'n',v:44927,z:'dd/mm/yyyy'},C28:{t:'s',v:'Aurixa'},C31:{t:'s',v:'31/02/2024'},A40:{t:'s',v:'Investment Property'},B40:{t:'s',v:'2 Beach Road'},D40:{t:'n',v:800000},I40:{t:'n',v:.06,z:'0.00%'},A53:{t:'s',v:'Credit Card'},E53:{t:'s',v:'$10,000'},F53:{t:'n',v:1000},H53:{t:'n',v:.2,z:'0%'}});sheet['!ref']='A1:J60'}else{sheet.A5={t:'s',v:'Childcare & Support'};sheet.B5={t:'s',v:'Childcare'};sheet.C5={t:'n',v:250};sheet.D5={t:'s',v:'After school care'};sheet.A9={t:'s',v:'Education'};sheet.B9={t:'s',v:'Higher Education / Vocational Training'};sheet.C9={t:'n',v:437};sheet.C55={t:'n',v:999999};sheet['!ref']='A1:D55'}XLSX.utils.book_append_sheet(book,sheet,name)}return XLSX.write(book,{type:'array',bookType:'xlsx'}) as ArrayBuffer}

describe('advanced Excel import',()=>{
  it.each(['client.xlsx','client.xls'])('accepts %s',name=>expect(validateExcelFile({name,size:100})).toBeNull());
  it('rejects unsupported and oversized files',()=>{expect(validateExcelFile({name:'client.csv',size:100})).toMatch(/Unsupported/);expect(validateExcelFile({name:'client.xlsx',size:MAX_EXCEL_FILE_BYTES+1})).toMatch(/10 MB/)});
  it.each([['Client Fact Find'],['Living Expenses']])('rejects a workbook missing %s',async missing=>{const result=await parseAdvancedClientWorkbook(workbook(['Client Fact Find','Living Expenses'].filter(name=>name!==missing)));expect(result.fatalErrors.join(' ')).toContain(missing)});
  it('maps applicants, addresses, employment and every fixed financial position',async()=>{const result=await parseAdvancedClientWorkbook(workbook());expect(result.fatalErrors).toEqual([]);expect(result.payload.applicants[0]).toMatchObject({firstName:'Alex',surname:'Smith',dateOfBirth:'2024-01-01'});expect(result.payload.applicants[1]).toMatchObject({firstName:'Taylor'});expect(result.payload.addresses[0]).toMatchObject({address:'1 Main Street',movedInDate:'2023-01-01'});expect(result.payload.employment[0].employerOrBusiness).toBe('Aurixa');expect(result.warnings.join(' ')).toMatch(/invalid date/);expect(result.payload.assets).toHaveLength(10);expect(result.payload.assets[0]).toMatchObject({assetType:'Investment Property',currentValue:800000,interestRate:6});expect(result.payload.assets[1].currentValue).toBe(0);expect(result.payload.liabilities).toHaveLength(8);expect(result.payload.liabilities[0]).toMatchObject({limitOrOriginalAmount:10000,currentBalance:1000,interestRate:20});expect(result.payload.expenses).toHaveLength(50);expect(result.payload.expenses[0]).toMatchObject({monthlyAmount:250,notes:'After school care'});expect(result.payload.expenses[4].monthlyAmount).toBe(437);expect(result.summary).toMatchObject({applicantsFound:2,addressesFound:1,employmentRecordsFound:1,assetsPopulated:1,liabilitiesPopulated:1,livingExpensesPopulated:2})});
  it('ignores workbook totals and recalculates with shared calculations',async()=>{const result=await parseAdvancedClientWorkbook(workbook());expect(result.payload.calculatedTotals).toEqual(calculateFactFindTotals(result.payload));expect(result.payload.calculatedTotals?.totalMonthlyLivingExpensesCents).toBe(68700)});
  it('parses the original workbook value without substituting an expense default',async()=>{const bytes=readFileSync('docs/reference/Aurixa Systems - White Label Client Fact Find Template.xlsx');expect(bytes.byteLength).toBeGreaterThan(0);const result=await parseAdvancedClientWorkbook(Uint8Array.from(bytes).buffer);expect(result.fatalErrors).toEqual([]);expect(result.payload.assets).toHaveLength(10);expect(result.payload.liabilities).toHaveLength(8);expect(result.payload.expenses).toHaveLength(50);expect(result.payload.expenses[4].monthlyAmount).toBe(600)});
});
