import * as XLSX from 'xlsx';
import { describe,expect,it } from 'vitest';
import { MAX_EXCEL_FILE_BYTES, parseAdvancedClientWorkbook, validateExcelFile } from './excelImport';

const workbook=(sheets=['Client Fact Find','Living Expenses'])=>{const book=XLSX.utils.book_new();for(const name of sheets){const sheet=XLSX.utils.aoa_to_sheet([]);if(name==='Client Fact Find'){sheet.C7={t:'s',v:'Alex'};sheet.C9={t:'s',v:'Smith'};sheet.G7={t:'s',v:'Taylor'};sheet.C19={t:'s',v:'1 Main Street'};sheet.C28={t:'s',v:'Aurixa'};sheet.A40={t:'s',v:'Investment Property'};sheet.B40={t:'s',v:'2 Beach Road'};sheet.D40={t:'n',v:800000};sheet.A53={t:'s',v:'Credit Card'};sheet.F53={t:'n',v:1000};sheet['!ref']='A1:J60'}else{sheet.C5={t:'n',v:250};sheet.D5={t:'s',v:'After school care'};sheet['!ref']='A1:D55'}XLSX.utils.book_append_sheet(book,sheet,name)}return XLSX.write(book,{type:'array',bookType:'xlsx'}) as ArrayBuffer};
describe('advanced Excel import',()=>{
 it.each(['client.xlsx','client.xls'])('accepts %s',name=>expect(validateExcelFile({name,size:100})).toBeNull());
 it('rejects unsupported and oversized files',()=>{expect(validateExcelFile({name:'client.csv',size:100})).toMatch(/Unsupported/);expect(validateExcelFile({name:'client.xlsx',size:MAX_EXCEL_FILE_BYTES+1})).toMatch(/10 MB/)});
 it('requires both source worksheets',()=>expect(()=>parseAdvancedClientWorkbook(workbook(['Client Fact Find']))).toThrow(/Living Expenses/));
 it('maps applicants, addresses, employment and all fixed financial positions',()=>{const result=parseAdvancedClientWorkbook(workbook());expect(result.payload.applicants[0]).toMatchObject({firstName:'Alex',surname:'Smith'});expect(result.payload.applicants[1]).toMatchObject({firstName:'Taylor'});expect(result.payload.addresses[0].address).toBe('1 Main Street');expect(result.payload.employment[0].employerOrBusiness).toBe('Aurixa');expect(result.payload.assets).toHaveLength(10);expect(result.payload.assets[0]).toMatchObject({assetType:'Investment Property',currentValue:800000});expect(result.payload.liabilities).toHaveLength(8);expect(result.payload.liabilities[0].currentBalance).toBe(1000);expect(result.payload.expenses).toHaveLength(50);expect(result.payload.expenses[0]).toMatchObject({monthlyAmount:250,notes:'After school care'});expect(result.payload.expenses[4].monthlyAmount).toBe(0);expect(result.summary).toMatchObject({applicantsFound:2,addressesFound:1,employmentRecordsFound:1,assetsPopulated:1,liabilitiesPopulated:1,livingExpensesPopulated:1})});
});
