import { describe,expect,it,vi } from 'vitest';
import { createAdvancedDefaults } from '@/components/clients/add-client/defaults';
import { isPropertyAsset,mapAdvancedToViewClient,saveAdvancedViewClientData } from './viewClientMapping';
describe('Advanced to View Client mapping',()=>{
 it('maps both applicants, addresses and employment without duplicate income records',()=>{const p=createAdvancedDefaults();Object.assign(p.applicants[0],{firstName:'Alex',surname:'Smith',middleName:'J',residencyStatus:'Citizen'});Object.assign(p.applicants[1]!,{firstName:'Taylor',surname:'Smith'});p.addresses[0].address='1 Main St';p.addresses[2].address='2 Other St';p.employment[0].employerOrBusiness='Aurixa';p.employment[0].baseSalary=100000;const m=mapAdvancedToViewClient(p);expect(m.personal).toMatchObject({primary_first_name:'Alex',secondary_first_name:'Taylor',current_address:'1 Main St',secondary_current_address:'2 Other St'});expect(m.addresses).toHaveLength(2);expect(m.employment).toHaveLength(1);expect(m.employment[0]).toMatchObject({contact_type:'primary',gross_annual_salary:100000});expect(m).not.toHaveProperty('income')});
 it('classifies clear property assets and leaves ambiguous assets in Financials',()=>{const p=createAdvancedDefaults();Object.assign(p.assets[0],{assetType:'Investment Property',descriptionOrAddress:'3 Coast Rd',currentValue:900000,loanBalance:400000,monthlyRepayment:2200});Object.assign(p.assets[1],{assetType:'Shares',descriptionOrAddress:'Index fund',currentValue:50000});expect(isPropertyAsset(p.assets[0])).toBe(true);const m=mapAdvancedToViewClient(p);expect(m.properties[0]).toMatchObject({address:'3 Coast Rd',value:900000,loan_remaining:400000});expect(m.assets[0]).toMatchObject({description:'Index fund',value:50000})});
 it('maps debt current balance, meaningful expenses, and skips blank fixed rows',()=>{const p=createAdvancedDefaults();Object.assign(p.liabilities[0],{liabilityType:'Credit Card',limitOrOriginalAmount:10000,currentBalance:1200,lender:'Bank'});p.expenses[0].notes='Shared care';const m=mapAdvancedToViewClient(p);expect(m.liabilities).toHaveLength(1);expect(m.liabilities[0]).toMatchObject({current_balance:1200,credit_limit:10000});expect(m.assets).toHaveLength(0);expect(m.expenses).toHaveLength(1)});
 it('saves through existing manage-client-data tables',async()=>{const p=createAdvancedDefaults();p.applicants[0].firstName='Alex';p.applicants[0].surname='Smith';p.assets[0].assetType='Savings';p.assets[0].currentValue=100;const invoke=vi.fn().mockResolvedValue({data:{success:true}});expect(await saveAdvancedViewClientData('client-1',p,invoke)).toEqual([]);expect(invoke).toHaveBeenCalledWith('manage-client-data',expect.objectContaining({operation:'update',table:'clients',clientId:'client-1'}));expect(invoke).toHaveBeenCalledWith('manage-client-data',expect.objectContaining({operation:'create',table:'client_assets',clientId:'client-1'}))});
});
